import {Theme} from "../theme.slint";

import { TitleBarView, TitleBarAdapter } from "./title_bar_view.slint";
export { TitleBarAdapter }

import { ShortcutBarView, ScanAdapter } from "./shortcut_bar_view.slint";
export { ScanAdapter }

import { FooterView, FooterAdapter } from "./footer_view.slint";
export { FooterAdapter }

import { PanelWindowView, PanelWindowAdapter } from "./docking/panel_window_view.slint";
export { PanelWindowView, PanelWindowAdapter }

import { DockRoot } from "./../widgets/docking/dock_root.slint";
export { DockRoot }

import { HSeparator } from "./../widgets/separator.slint";
import { ContextMenu } from "./../widgets/context_menu/context_menu.slint";
import { ContextMenuItem } from "./../widgets/context_menu/context_menu_item.slint";
import { ToolbarMenu } from "./../widgets/toolbar_menu/toolbar_menu.slint";
import { ToolbarMenuItem } from "./../widgets/toolbar_menu/toolbar_menu_item.slint";

export component MainWindowView inherits Window {
    title: @tr("Squalr");
    default-font-family: "Segoe UI";
    default-font-size: 10pt;
    default-font-weight: 525;
    preferred-width: 1280px;
    preferred-height: 840px;
    background: transparent;
    no-frame: true;
    VerticalLayout {
        title-bar := TitleBarView {
            title: @tr("Squalr");
        }

        toolbar-menu := ToolbarMenu {
            menus: [
                { header: "File", items:[{ text:"Select Project" }, { text:"Exit Squalr" }] },
                { header: "Edit", items:[{ text:"Settings" }] },
                { header: "Layout", items:[{ text:"Reset Layout" }] },
                {
                    header: "Windows",
                    items:[
                        { text:"Process Selector" },
                        { text:"Project Explorer" },
                        { text:"Property Viewer" },
                        { text:"Memory Viewer" },
                        { text:"Scan Results" },
                        { text:"Pointer Scan Results" },
                        { text:"Snapshot Manager" },
                        { text:".NET Explorer" },
                    ]
                },
                { header: "Scans", items:[{ text:"Pointer Scan" }] },
                { header: "Debugger", items:[{ text:"Disassembly" }, { text:"Code Tracer" }] },
            ];
        }

        shortcut-bar := ShortcutBarView { }

        dock-root := DockRoot { }

        footer := FooterView { }
    }
}
