import {Theme} from "../theme.slint";

import { TitleBarView, TitleBarAdapter } from "./title_bar_view.slint";
export { TitleBarAdapter }

import { FooterView, FooterAdapter } from "./footer_view.slint";
export { FooterAdapter }

import { DockRoot } from "./docking/dock_root.slint";
export { DockRoot }

import { PanelWindowView, PanelWindowAdapter } from "./docking/panel_window_view.slint";
export { PanelWindowView, PanelWindowAdapter }

export component MainWindowView inherits Window {
    preferred-width: 1280px;
    preferred-height: 840px;
    background: transparent;
    no-frame: true;
    title: @tr("Squalr");
    VerticalLayout {
        title-bar := TitleBarView {
            title: @tr("Squalr");
        }

        // File/Edit/etc menu bar
        Rectangle {
            background: Theme.background-primary;
            height: 24px;
            menu-bar := HorizontalLayout {
                alignment: start;
                spacing: 8px;
                padding-left: 8px;
                file-header-button := Rectangle {
                    file-menu := PopupWindow {
                        Rectangle {
                            height: 100%;
                            width: 100%;
                            background: Theme.background-primary;
                            VerticalLayout {
                                padding-left: 8px;
                                padding-right: 8px;
                                padding-top: 4px;
                                padding-bottom: 4px;
                                spacing: 8px;
                                select-project := Text {
                                    font-size: 10pt;
                                    color: Theme.foreground;
                                    text: "Select Project";
                                }

                                Rectangle {
                                    height: 2px;
                                    width: 100%;
                                    background: Theme.foreground;
                                }

                                exit-app := Text {
                                    font-size: 10pt;
                                    color: Theme.foreground;
                                    text: "Exit Squalr";
                                }
                            }
                        }

                        x: 20px;
                        y: 20px;
                    }

                    file-header-touch-area := TouchArea {
                        clicked => {
                            file-menu.show()
                        }
                    }

                    title := Text {
                        text: "File";
                        font-size: 10pt;
                        color: Theme.foreground;
                    }
                }
            }
        }

        dock-root := DockRoot { }

        footer := FooterView { }
    }
}
