import { Theme } from "./../theme.slint";

import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { TextButton } from "../components/buttons/text_button.slint";

export component SettingsView inherits Rectangle {
    background: Theme.background-panel;
    border-color: Theme.submenu-border;
    border-radius: 2px;
    border-width: 1px;
    content := VerticalBox {
        padding: 0px;
        spacing: 0px;
        header := HorizontalBox {
            alignment: start;
            padding: 0px;
            spacing: 0px;
            height: 24px;
            TextButton {
                text: "General";
            }

            TextButton {
                text: "Memory";
            }

            TextButton {
                text: "Intervals";
            }

            TextButton {
                text: "Middleware";
            }
        }

        HorizontalBox {
            vertical-stretch: 100%;
            Text {
                text: "Suh";
            }
        }
    }
}
