import { Theme } from "../theme.slint";
import { WindowViewModelBindings } from "./../view_model_bindings.slint";

import { HorizontalBox, VerticalBox, Palette, Button } from "std-widgets.slint";
import { IconButton } from "../components/buttons/icon_button.slint";
import { TextField } from "../components/input/text_field.slint";

import { ProcessQuickSelector } from "./../controls/process_quick_selector_control.slint";
import { DataTypeSelector } from "../controls/data_type_selector.slint";
import { ScanConstraintTypeSelector } from "../controls/scan_constraint_selector.slint";

export component ShortcutBarView inherits Rectangle {
    height: 24px;
    Rectangle {
        background: Theme.background-primary;
        HorizontalLayout {
            // Shortcut
            HorizontalBox {
                alignment: start;
                padding-left: 4px;
                padding-right: 0px;
                padding-top: 0px;
                padding-bottom: 0px;
                spacing: 4px;
                select-process-button := IconButton {
                    icon: @image-url("../images/select_process.png");
                    tooltip-text: @tr("Select Process");
                    icon-width: 24px;
                    icon-height: 24px;
                    width: 36px;
                    clicked => {
                    }
                }

                open-project-button := IconButton {
                    icon: @image-url("../images/file_system/open_folder.png");
                    tooltip-text: @tr("Open Project");
                    icon-width: 24px;
                    icon-height: 24px;
                    width: 36px;
                    clicked => {
                    }
                }

                process-quick-selector := ProcessQuickSelector {
                    selected-process-name: "Temp test";
                }

                data-type-selector := DataTypeSelector { }

                new-scan-button := IconButton {
                    icon: @image-url("../images/scans/scan_new.png");
                    tooltip-text: @tr("New Scan");
                    icon-width: 24px;
                    icon-height: 24px;
                    width: 36px;
                    clicked => {
                    }
                }

                collect-values-button := IconButton {
                    icon: @image-url("../images/scans/scan_collect_values.png");
                    tooltip-text: @tr("Collect Values");
                    icon-width: 24px;
                    icon-height: 24px;
                    width: 36px;
                    clicked => {
                    }
                }

                scan-constraint-selector := ScanConstraintTypeSelector { }

                scan-value := TextField {
                    width: 192px;
                    preview-text: "Enter a scan value...";
                }

                start-scan-button := IconButton {
                    icon: @image-url("../images/navigation/right_arrow.png");
                    tooltip-text: @tr("Start Scan");
                    icon-width: 24px;
                    icon-height: 24px;
                    width: 36px;
                    clicked => {
                    }
                }
            }
        }
    }
}
