import { HorizontalBox, VerticalBox, Palette, Button } from "std-widgets.slint";
import { IconButton } from "../widgets/icon_button.slint";
import { Theme } from "../theme.slint";


export global TitleBarAdapter {
    callback close();
    callback maximize();
    callback minimize();
    callback double-clicked();
    callback drag(int, int);
}

export component TitleBarView inherits Rectangle {
    in property <string> title <=> title.text;
    height: 32px;
    Rectangle {
        border-top-left-radius: 8px;
        border-top-right-radius: 8px;
        background: Theme.background-primary;
        title-drag := TouchArea {
            double-clicked => {
                if (self.pressed && self.enabled) {
                    TitleBarAdapter.double-clicked();
                }
            }
            moved => {
                if (self.pressed && self.enabled) {
                    TitleBarAdapter.drag((title-drag.mouse-x - title-drag.pressed-x) / 1px, (title-drag.mouse-y - title-drag.pressed-y) / 1px);
                }
            }
        }

        HorizontalLayout {
            padding-top: 4px;
            padding-left: 8px;
            spacing: 8px;
            app_icon := Image {
                source: @image-url("../images/app/app_icon.png");
                width: 24px;
            }

            title := Text {
                vertical-alignment: center;
                font-size: 10pt;
                color: Theme.foreground;
            }

            minimize-button := IconButton {
                icon: @image-url("../images/app/minimize.png");
                accessible-label: @tr("Minimize");
                width: 24px;
                clicked => {
                    TitleBarAdapter.minimize()
                }
            }

            maximize-button := IconButton {
                icon: @image-url("../images/app/maximize.png");
                accessible-label: @tr("Maximize");
                width: 24px;
                clicked => {
                    TitleBarAdapter.maximize()
                }
            }

            close-button := IconButton {
                icon: @image-url("../images/app/close.png");
                accessible-label: @tr("Close");
                width: 24px;
                clicked => {
                    TitleBarAdapter.close()
                }
            }
        }
    }
}
