import { Theme } from "../../../theme.slint";

import { ConversionsViewModelBindings, ScanSettingsViewModelBindings, FloatingPointToleranceView } from "../../../view_model_bindings.slint";
import { FloatingPointToleranceIconConverter } from "../../../converters/floating_point_tolerance_icon_converter.slint";
import { GroupBox } from "../../../components/groupbox.slint";
import { Button } from "../../../components/buttons/button.slint";
import { TextField } from "../../../components/input/text_field.slint";
import { Checkbox } from "../../../components/checkboxes/checkbox.slint";
import { TextCheckbox } from "../../../components/checkboxes/text_checkbox.slint";
import { BevelButton } from "../../../components/buttons/bevel_button.slint";
import { ContextMenu } from "../../../components/context_menu/context_menu.slint";

export component SettingChooserFloatingPointTolerance inherits Rectangle {
    floating_point_tolerance_icon_converter := FloatingPointToleranceIconConverter { }

    HorizontalLayout {
        padding: 0px;
        spacing: 0px;
        floating_point_tolerance_dropdown_button := Button {
            height: 24px;
            clicked => {
                floating_point_tolerance_context_menu.show();
            }
            Rectangle {
                background: Theme.background_control;
                border_color: Theme.submenu_border;
                border_width: 1px;
                border_radius: 1px;
                VerticalLayout {
                    alignment: center;
                    HorizontalLayout {
                        padding_left: 4px;
                        padding_right: 8px;
                        alignment: start;
                        spacing: 8px;
                        Image {
                            width: 16px;
                            height: 16px;
                            horizontal_alignment: center;
                            vertical_alignment: center;
                            source: floating_point_tolerance_icon_converter.floating_point_tolerance_source(ScanSettingsViewModelBindings.floating_point_tolerance);
                        }

                        Text {
                            color: Theme.foreground;
                            horizontal_alignment: left;
                            vertical_alignment: center;
                            text: ConversionsViewModelBindings.get_floating_point_tolerance_string(ScanSettingsViewModelBindings.floating_point_tolerance);
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: end;
                padding_right: 4px;
                Image {
                    source: @image_url("../../../images/navigation/down_arrow_small.png");
                }
            }

            HorizontalLayout {
                alignment: end;
                padding_right: 24px;
                Rectangle {
                    background: Theme.submenu_border;
                    width: 1px;
                }
            }
        }
    }

    floating_point_tolerance_context_menu := ContextMenu {
        close_policy: close_on_click_outside;
        x: floating_point_tolerance_dropdown_button.x;
        y: floating_point_tolerance_dropdown_button.y + floating_point_tolerance_dropdown_button.height;
        Rectangle {
            background: Theme.background_control;
            border_color: Theme.submenu_border;
            border_width: 1px;
            min_width: floating_point_tolerance_dropdown_button.width - self.border_width * 2 + 8px;
            VerticalLayout {
                padding: 0px;
                spacing: 0px;
                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.floating_point_tolerance = FloatingPointToleranceView.tolerance_10e1;
                        ScanSettingsViewModelBindings.floating_point_tolerance_changed(FloatingPointToleranceView.tolerance_10e1);
                        floating_point_tolerance_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            padding: 0px;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: floating_point_tolerance_icon_converter.floating_point_tolerance_source(FloatingPointToleranceView.tolerance_10e1);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_floating_point_tolerance_string(FloatingPointToleranceView.tolerance_10e1);
                            }
                        }
                    }
                }

                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.floating_point_tolerance = FloatingPointToleranceView.tolerance_10e2;
                        ScanSettingsViewModelBindings.floating_point_tolerance_changed(FloatingPointToleranceView.tolerance_10e2);
                        floating_point_tolerance_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: floating_point_tolerance_icon_converter.floating_point_tolerance_source(FloatingPointToleranceView.tolerance_10e2);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_floating_point_tolerance_string(FloatingPointToleranceView.tolerance_10e2);
                            }
                        }
                    }
                }

                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.floating_point_tolerance = FloatingPointToleranceView.tolerance_10e3;
                        ScanSettingsViewModelBindings.floating_point_tolerance_changed(FloatingPointToleranceView.tolerance_10e3);
                        floating_point_tolerance_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: floating_point_tolerance_icon_converter.floating_point_tolerance_source(FloatingPointToleranceView.tolerance_10e3);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_floating_point_tolerance_string(FloatingPointToleranceView.tolerance_10e3);
                            }
                        }
                    }
                }

                Button {
                    clicked => {
                        ScanSettingsViewModelBindings.floating_point_tolerance = FloatingPointToleranceView.tolerance_10e4;
                        ScanSettingsViewModelBindings.floating_point_tolerance_changed(FloatingPointToleranceView.tolerance_10e4);
                        floating_point_tolerance_context_menu.close();
                    }
                    height: 24px;
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: floating_point_tolerance_icon_converter.floating_point_tolerance_source(FloatingPointToleranceView.tolerance_10e4);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_floating_point_tolerance_string(FloatingPointToleranceView.tolerance_10e4);
                            }
                        }
                    }
                }

                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.floating_point_tolerance = FloatingPointToleranceView.tolerance_10e5;
                        ScanSettingsViewModelBindings.floating_point_tolerance_changed(FloatingPointToleranceView.tolerance_10e5);
                        floating_point_tolerance_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: floating_point_tolerance_icon_converter.floating_point_tolerance_source(FloatingPointToleranceView.tolerance_10e5);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_floating_point_tolerance_string(FloatingPointToleranceView.tolerance_10e5);
                            }
                        }
                    }
                }

                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.floating_point_tolerance = FloatingPointToleranceView.tolerance_epsilon;
                        ScanSettingsViewModelBindings.floating_point_tolerance_changed(FloatingPointToleranceView.tolerance_epsilon);
                        floating_point_tolerance_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: floating_point_tolerance_icon_converter.floating_point_tolerance_source(FloatingPointToleranceView.tolerance_epsilon);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_floating_point_tolerance_string(FloatingPointToleranceView.tolerance_epsilon);
                            }
                        }
                    }
                }
            }
        }
    }
}
