import { Theme } from "../../../theme.slint";

import { ConversionsViewModelBindings, ScanSettingsViewModelBindings, MemoryAlignmentView } from "../../../view_model_bindings.slint";
import { MemoryAlignmentIconConverter } from "../../../converters/memory_alignment_icon_converter.slint";
import { GroupBox } from "../../../components/groupbox.slint";
import { Button } from "../../../components/buttons/button.slint";
import { TextField } from "../../../components/input/text_field.slint";
import { Checkbox } from "../../../components/checkboxes/checkbox.slint";
import { TextCheckbox } from "../../../components/checkboxes/text_checkbox.slint";
import { BevelButton } from "../../../components/buttons/bevel_button.slint";
import { ContextMenu } from "../../../components/context_menu/context_menu.slint";

export component SettingChooserMemoryAlignment inherits Rectangle {
    memory_alignment_icon_converter := MemoryAlignmentIconConverter { }

    min_width: 96px;
    HorizontalLayout {
        padding: 0px;
        spacing: 0px;
        memory_alignment_dropdown_button := Button {
            height: 24px;
            clicked => {
                memory_alignment_context_menu.show();
            }
            Rectangle {
                background: Theme.background_control;
                border_color: Theme.submenu_border;
                border_width: 1px;
                border_radius: 1px;
                VerticalLayout {
                    alignment: center;
                    HorizontalLayout {
                        padding_left: 4px;
                        padding_right: 8px;
                        alignment: start;
                        spacing: 8px;
                        Image {
                            width: 16px;
                            height: 16px;
                            horizontal_alignment: center;
                            vertical_alignment: center;
                            source: memory_alignment_icon_converter.memory_alignment_source(ScanSettingsViewModelBindings.memory_alignment);
                        }

                        Text {
                            color: Theme.foreground;
                            horizontal_alignment: left;
                            vertical_alignment: center;
                            text: ConversionsViewModelBindings.get_memory_alignment_string(ScanSettingsViewModelBindings.memory_alignment);
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: end;
                padding_right: 4px;
                Image {
                    source: @image_url("../../../images/navigation/down_arrow_small.png");
                }
            }

            HorizontalLayout {
                alignment: end;
                padding_right: 24px;
                Rectangle {
                    background: Theme.submenu_border;
                    width: 1px;
                }
            }
        }
    }

    memory_alignment_context_menu := ContextMenu {
        close_policy: close_on_click_outside;
        x: memory_alignment_dropdown_button.x;
        y: memory_alignment_dropdown_button.y + memory_alignment_dropdown_button.height;
        Rectangle {
            background: Theme.background_control;
            border_color: Theme.submenu_border;
            border_width: 1px;
            min_width: memory_alignment_dropdown_button.width - self.border_width * 2;
            VerticalLayout {
                padding: 0px;
                spacing: 0px;
                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.memory_alignment = MemoryAlignmentView.alignment_1;
                        ScanSettingsViewModelBindings.memory_alignment_changed(MemoryAlignmentView.alignment_1);
                        memory_alignment_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            padding: 0px;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: memory_alignment_icon_converter.memory_alignment_source(MemoryAlignmentView.alignment_1);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_memory_alignment_string(MemoryAlignmentView.alignment_1);
                            }
                        }
                    }
                }

                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.memory_alignment = MemoryAlignmentView.alignment_2;
                        ScanSettingsViewModelBindings.memory_alignment_changed(MemoryAlignmentView.alignment_2);
                        memory_alignment_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: memory_alignment_icon_converter.memory_alignment_source(MemoryAlignmentView.alignment_2);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_memory_alignment_string(MemoryAlignmentView.alignment_2);
                            }
                        }
                    }
                }

                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.memory_alignment = MemoryAlignmentView.alignment_4;
                        ScanSettingsViewModelBindings.memory_alignment_changed(MemoryAlignmentView.alignment_4);
                        memory_alignment_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: memory_alignment_icon_converter.memory_alignment_source(MemoryAlignmentView.alignment_4);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_memory_alignment_string(MemoryAlignmentView.alignment_4);
                            }
                        }
                    }
                }

                Button {
                    height: 24px;
                    clicked => {
                        ScanSettingsViewModelBindings.memory_alignment = MemoryAlignmentView.alignment_8;
                        ScanSettingsViewModelBindings.memory_alignment_changed(MemoryAlignmentView.alignment_8);
                        memory_alignment_context_menu.close();
                    }
                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            padding_left: 4px;
                            padding_right: 8px;
                            spacing: 8px;
                            alignment: start;
                            Image {
                                width: 16px;
                                height: 16px;
                                horizontal_alignment: center;
                                vertical_alignment: center;
                                source: memory_alignment_icon_converter.memory_alignment_source(MemoryAlignmentView.alignment_8);
                            }

                            Text {
                                color: Theme.foreground;
                                horizontal_alignment: left;
                                vertical_alignment: center;
                                text: ConversionsViewModelBindings.get_memory_alignment_string(MemoryAlignmentView.alignment_8);
                            }
                        }
                    }
                }
            }
        }
    }
}
