import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { ToolbarMenuItem, ToolbarMenuItemData } from "toolbar_menu_item.slint";
import { DockFocusCatcher } from "../../views/docking/drag_and_drop/dock_focus_catcher.slint";

export struct ToolbarMenuData {
    header: string,
    items: [ToolbarMenuItemData],
}

export component ToolbarMenu inherits Rectangle {
    in_out property <[ToolbarMenuData]> menus;
    in property <length> bottom_padding: 4px;
    callback onItemClicked(string);
    height: 24px + root.bottom_padding;
    background: Theme.background_primary;
    HorizontalLayout {
        content := HorizontalBox {
            alignment: start;
            padding_left: 0px;
            padding_right: 0px;
            padding_top: 0px;
            padding_bottom: bottom_padding;
            spacing: 0px;
            for menu in menus: ToolbarMenuItem {
                parent_toolbar_size: content.width;
                text: menu.header;
                items: menu.items;
                onItemClicked(key) => {
                    root.onItemClicked(key);
                }
            }
        }

        fill := Rectangle {
            horizontal_stretch: 100%;
        }
    }

    DockFocusCatcher { }
}
