import { HorizontalBox, VerticalBox } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { ScanSettingsViewModelBindings, MemorySettingsViewModelBindings } from "../../view_model_bindings.slint";

import { SettingsTabMemory } from "settings_tab_memory.slint";
import { SettingsTabScan } from "settings_tab_scan.slint";
import { GroupBox } from "../../components/groupbox.slint";
import { Button } from "../../components/buttons/button.slint";
import { TextField } from "../../components/input/text_field.slint";
import { Checkbox } from "../../components/checkboxes/checkbox.slint";
import { TextCheckbox } from "../../components/checkboxes/text_checkbox.slint";
import { BevelButton } from "../../components/buttons/bevel_button.slint";

export component SettingsView inherits Rectangle {
    property <int> selected_tab: 1;
    content := VerticalBox {
        padding: 0px;
        spacing: 0px;
        Rectangle {
            height: 24px;
            padding_bottom: 4px;
            header := HorizontalBox {
                alignment: start;
                padding: 0px;
                spacing: 0px;
                general_tab := BevelButton {
                    width: 96px;
                    height: 24px;
                    border_color: Theme.submenu_border;
                    border_width: 1px;
                    border_radius: 0px;
                    border_top_left_radius: 8px;
                    border_top_right_radius: 8px;
                    border_bottom_left_radius: 0px;
                    border_bottom_right_radius: 0px;
                    clicked => {
                        root.selected_tab = 0;
                    }
                    Text {
                        horizontal_alignment: left;
                        vertical_alignment: center;
                        text: @tr("General");
                        color: Theme.foreground;
                    }
                }

                memory_tab := BevelButton {
                    width: 96px;
                    height: 24px;
                    border_color: Theme.submenu_border;
                    border_width: 1px;
                    border_radius: 0px;
                    border_top_left_radius: 8px;
                    border_top_right_radius: 8px;
                    border_bottom_left_radius: 0px;
                    border_bottom_right_radius: 0px;
                    clicked => {
                        root.selected_tab = 1;
                    }
                    Text {
                        horizontal_alignment: left;
                        vertical_alignment: center;
                        text: @tr("Memory");
                        color: Theme.foreground;
                    }
                }

                scans_tab := BevelButton {
                    width: 96px;
                    height: 24px;
                    border_color: Theme.submenu_border;
                    border_width: 1px;
                    border_radius: 0px;
                    border_top_left_radius: 8px;
                    border_top_right_radius: 8px;
                    border_bottom_left_radius: 0px;
                    border_bottom_right_radius: 0px;
                    clicked => {
                        root.selected_tab = 2;
                    }
                    Text {
                        horizontal_alignment: left;
                        vertical_alignment: center;
                        text: @tr("Scan");
                        color: Theme.foreground;
                    }
                }

                middleware_tab := BevelButton {
                    width: 96px;
                    height: 24px;
                    border_color: Theme.submenu_border;
                    border_width: 1px;
                    border_radius: 0px;
                    border_top_left_radius: 8px;
                    border_top_right_radius: 8px;
                    border_bottom_left_radius: 0px;
                    border_bottom_right_radius: 0px;
                    clicked => {
                        root.selected_tab = 3;
                    }
                    Text {
                        horizontal_alignment: left;
                        vertical_alignment: center;
                        text: @tr("Middleware");
                        color: Theme.foreground;
                    }
                }

                states [
                    _ when root.selected_tab >= 0: {
                        general_tab.background_color: root.selected_tab == 0 ? Theme.background_control_primary : Theme.background_control_secondary;
                        memory_tab.background_color: root.selected_tab == 1 ? Theme.background_control_primary : Theme.background_control_secondary;
                        scans_tab.background_color: root.selected_tab == 2 ? Theme.background_control_primary : Theme.background_control_secondary;
                        middleware_tab.background_color: root.selected_tab == 3 ? Theme.background_control_primary : Theme.background_control_secondary;
                    }
                ]
            }
        }

        Rectangle {
            general_content := VerticalBox { }

            memory_content := SettingsTabMemory { }

            scans_content := SettingsTabScan { }

            middleware_content := VerticalBox { }
        }

        states [
            _ when root.selected_tab >= 0: {
                general_content.visible: root.selected_tab == 0;
                memory_content.visible: root.selected_tab == 1;
                scans_content.visible: root.selected_tab == 2;
                middleware_content.visible: root.selected_tab == 3;
            }
        ]
    }
}
