import { HorizontalBox, VerticalBox } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { ScanSettingsViewModelBindings, MemorySettingsViewModelBindings } from "../../view_model_bindings.slint";

import { TabMemorySettings } from "tab_memory_settings.slint";
import { TabScanSettings } from "tab_scan_settings.slint";
import { GroupBox } from "../../components/groupbox.slint";
import { Button } from "../../components/buttons/button.slint";
import { TextField } from "../../components/input/text_field.slint";
import { Checkbox } from "../../components/checkboxes/checkbox.slint";
import { TextCheckbox } from "../../components/checkboxes/text_checkbox.slint";
import { BevelButton } from "../../components/buttons/bevel_button.slint";

export component SettingsView inherits Rectangle {
    property <int> selected-tab: 1;
    content := VerticalBox {
        padding: 0px;
        spacing: 0px;
        Rectangle {
            height: 24px;
            padding-bottom: 4px;
            header := HorizontalBox {
                alignment: start;
                padding: 0px;
                spacing: 0px;
                general-tab := BevelButton {
                    width: 96px;
                    height: 24px;
                    border-color: Theme.submenu-border;
                    border-width: 1px;
                    border-radius: 0px;
                    border-top-left-radius: 8px;
                    border-top-right-radius: 8px;
                    border-bottom-left-radius: 0px;
                    border-bottom-right-radius: 0px;
                    clicked => {
                        root.selected-tab = 0;
                    }
                    Text {
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        text: @tr("General");
                        color: Theme.foreground;
                    }
                }

                memory-tab := BevelButton {
                    width: 96px;
                    height: 24px;
                    border-color: Theme.submenu-border;
                    border-width: 1px;
                    border-radius: 0px;
                    border-top-left-radius: 8px;
                    border-top-right-radius: 8px;
                    border-bottom-left-radius: 0px;
                    border-bottom-right-radius: 0px;
                    clicked => {
                        root.selected-tab = 1;
                    }
                    Text {
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        text: @tr("Memory");
                        color: Theme.foreground;
                    }
                }

                scans-tab := BevelButton {
                    width: 96px;
                    height: 24px;
                    border-color: Theme.submenu-border;
                    border-width: 1px;
                    border-radius: 0px;
                    border-top-left-radius: 8px;
                    border-top-right-radius: 8px;
                    border-bottom-left-radius: 0px;
                    border-bottom-right-radius: 0px;
                    clicked => {
                        root.selected-tab = 2;
                    }
                    Text {
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        text: @tr("Scan");
                        color: Theme.foreground;
                    }
                }

                middleware-tab := BevelButton {
                    width: 96px;
                    height: 24px;
                    border-color: Theme.submenu-border;
                    border-width: 1px;
                    border-radius: 0px;
                    border-top-left-radius: 8px;
                    border-top-right-radius: 8px;
                    border-bottom-left-radius: 0px;
                    border-bottom-right-radius: 0px;
                    clicked => {
                        root.selected-tab = 3;
                    }
                    Text {
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        text: @tr("Middleware");
                        color: Theme.foreground;
                    }
                }

                states [
                    _ when root.selected-tab >= 0: {
                        general-tab.background-color: root.selected-tab == 0 ? Theme.background-control-primary : Theme.background-control-secondary;
                        memory-tab.background-color: root.selected-tab == 1 ? Theme.background-control-primary : Theme.background-control-secondary;
                        scans-tab.background-color: root.selected-tab == 2 ? Theme.background-control-primary : Theme.background-control-secondary;
                        middleware-tab.background-color: root.selected-tab == 3 ? Theme.background-control-primary : Theme.background-control-secondary;
                    }
                ]
            }
        }

        Rectangle {
            general-content := VerticalBox { }

            memory-content := TabMemorySettings { }

            scans-content := TabScanSettings { }

            middleware-content := VerticalBox { }
        }

        states [
            _ when root.selected-tab >= 0: {
                general-content.visible: root.selected-tab == 0;
                memory-content.visible: root.selected-tab == 1;
                scans-content.visible: root.selected-tab == 2;
                middleware-content.visible: root.selected-tab == 3;
            }
        ]
    }
}
