import { HorizontalBox, VerticalBox, ScrollView } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { ScanSettingsViewModelBindings, MemorySettingsViewModelBindings } from "../../view_model_bindings.slint";

import { GroupBox } from "../../components/groupbox.slint";
import { Button } from "../../components/buttons/button.slint";
import { TextField } from "../../components/input/text_field.slint";
import { Checkbox } from "../../components/checkboxes/checkbox.slint";
import { TextCheckbox } from "../../components/checkboxes/text_checkbox.slint";
import { BevelButton } from "../../components/buttons/bevel_button.slint";
import { ContextMenu } from "../../components/context_menu/context_menu.slint";

export component TabScanSettings inherits Rectangle {
    GridLayout {
        padding: 8px;
        spacing: 8px;
        Row {
            GroupBox {
                header-text: "Memory Read Intervals";
                VerticalBox {
                    alignment: start;
                    padding: 0px;
                    spacing: 6px;
                    GridLayout {
                        spacing: 8px;
                        Row {
                            TextField {
                                height: 24px;
                                width: 72px;
                                default-text: "50";
                            }

                            Text {
                                vertical-alignment: center;
                                text: @tr("Freeze Interval (ms)");
                                color: Theme.foreground;
                            }
                        }

                        Row {
                            TextField {
                                height: 24px;
                                default-text: "100";
                            }

                            Text {
                                vertical-alignment: center;
                                text: @tr("Project Read Interval (ms)");
                                color: Theme.foreground;
                            }
                        }

                        Row {
                            TextField {
                                height: 24px;
                                default-text: "100";
                            }

                            Text {
                                vertical-alignment: center;
                                text: @tr("Result Read Interval (ms)");
                                color: Theme.foreground;
                            }
                        }
                    }
                }
            }

            GroupBox {
                header-text: "Scan Internals";
                VerticalBox {
                    alignment: start;
                    padding: 0px;
                    spacing: 6px;
                    TextCheckbox {
                        text: @tr("Single-Threaded Scan");
                        is-checked <=> MemorySettingsViewModelBindings.required_write;
                        check-changed(value) => {
                            MemorySettingsViewModelBindings.required_write_changed(value);
                        }
                    }

                    TextCheckbox {
                        text: @tr("Perform Extra Debug Scan");
                        is-checked <=> MemorySettingsViewModelBindings.required_execute;
                        check-changed(value) => {
                            MemorySettingsViewModelBindings.required_execute_changed(value);
                        }
                    }
                }
            }
        }

        GroupBox {
            header-text: "Scan Params";
            VerticalBox {
                alignment: start;
                padding: 0px;
                spacing: 6px;
                GridLayout {
                    spacing: 8px;
                    Row {
                        Rectangle {
                            min-width: 96px;
                            HorizontalLayout {
                                padding: 0px;
                                spacing: 0px;
                                memory-alignment-dropdown-button := Button {
                                    height: 24px;
                                    clicked => {
                                        memory-alignment-context-menu.show();
                                    }
                                    VerticalLayout {
                                        alignment: center;
                                        HorizontalLayout {
                                            padding-left: 4px;
                                            alignment: start;
                                            Text {
                                                color: Theme.foreground;
                                                horizontal-alignment: left;
                                                vertical-alignment: center;
                                                text: "{Align}";
                                            }
                                        }
                                    }

                                    HorizontalLayout {
                                        alignment: end;
                                        padding-right: 4px;
                                        Image {
                                            source: @image-url("../../images/navigation/down_arrow_small.png");
                                        }
                                    }

                                    HorizontalLayout {
                                        alignment: end;
                                        padding-right: 24px;
                                        Rectangle {
                                            background: Theme.submenu-border;
                                            width: 1px;
                                        }
                                    }
                                }
                            }

                            memory-alignment-context-menu := ContextMenu {
                                close-policy: close-on-click-outside;
                                x: memory-alignment-dropdown-button.x;
                                y: memory-alignment-dropdown-button.y + memory-alignment-dropdown-button.height;
                                Rectangle {
                                    background: Theme.background-control;
                                    border-color: Theme.submenu-border;
                                    border-width: 1px;
                                    min-width: memory-alignment-dropdown-button.width - self.border-width * 2;
                                    VerticalBox {
                                        padding: 0px;
                                        spacing: 0px;
                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/data_types/purple_blocks_1.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "1";
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/data_types/purple_blocks_2.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "2";
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/data_types/purple_blocks_4.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "4";
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/data_types/purple_blocks_8.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "8";
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        Text {
                            vertical-alignment: center;
                            text: @tr("Memory Alignment");
                            color: Theme.foreground;
                        }
                    }

                    Row {
                        Rectangle {
                            HorizontalLayout {
                                padding: 0px;
                                spacing: 0px;
                                floating-point-tolerance-dropdown-button := Button {
                                    height: 24px;
                                    clicked => {
                                        floating-point-tolerance-context-menu.show();
                                    }
                                    VerticalLayout {
                                        alignment: center;
                                        HorizontalLayout {
                                            padding-left: 4px;
                                            alignment: start;
                                            Text {
                                                color: Theme.foreground;
                                                horizontal-alignment: left;
                                                vertical-alignment: center;
                                                text: "{Tolerance}";
                                            }
                                        }
                                    }

                                    HorizontalLayout {
                                        alignment: end;
                                        padding-right: 4px;
                                        Image {
                                            source: @image-url("../../images/navigation/down_arrow_small.png");
                                        }
                                    }

                                    HorizontalLayout {
                                        alignment: end;
                                        padding-right: 24px;
                                        Rectangle {
                                            background: Theme.submenu-border;
                                            width: 1px;
                                        }
                                    }
                                }
                            }

                            floating-point-tolerance-context-menu := ContextMenu {
                                close-policy: close-on-click-outside;
                                x: floating-point-tolerance-dropdown-button.x;
                                y: floating-point-tolerance-dropdown-button.y + floating-point-tolerance-dropdown-button.height;
                                Rectangle {
                                    background: Theme.background-control;
                                    border-color: Theme.submenu-border;
                                    border-width: 1px;
                                    min-width: floating-point-tolerance-dropdown-button.width - self.border-width * 2 + 8px;
                                    VerticalBox {
                                        padding: 0px;
                                        spacing: 0px;
                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/settings/tolerance_1.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "0.1";
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/settings/tolerance_2.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "0.01";
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/settings/tolerance_3.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "0.001";
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/settings/tolerance_4.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "0.0001";
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/settings/tolerance_5.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "0.00001";
                                                        }
                                                    }
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            VerticalLayout {
                                                alignment: center;
                                                HorizontalLayout {
                                                    padding-left: 4px;
                                                    alignment: start;
                                                    HorizontalBox {
                                                        padding: 0px;
                                                        Image {
                                                            width: 16px;
                                                            height: 16px;
                                                            horizontal-alignment: center;
                                                            vertical-alignment: center;
                                                            source: @image-url("../../images/settings/tolerance_6.png");
                                                        }

                                                        Text {
                                                            color: Theme.foreground;
                                                            horizontal-alignment: left;
                                                            vertical-alignment: center;
                                                            text: "Epsilon";
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        Text {
                            vertical-alignment: center;
                            text: @tr("Floating Point Tolerance");
                            color: Theme.foreground;
                        }
                    }

                    Row {
                        Rectangle {
                            HorizontalLayout {
                                padding: 0px;
                                spacing: 0px;
                                memory-read-mode-dropdown-button := Button {
                                    height: 24px;
                                    clicked => {
                                        memory-read-mode-context-menu.show();
                                    }
                                    VerticalLayout {
                                        alignment: center;
                                        HorizontalLayout {
                                            padding-left: 4px;
                                            alignment: start;
                                            Text {
                                                color: Theme.foreground;
                                                horizontal-alignment: left;
                                                vertical-alignment: center;
                                                text: "{Mode}";
                                            }
                                        }
                                    }

                                    HorizontalLayout {
                                        alignment: end;
                                        padding-right: 4px;
                                        Image {
                                            source: @image-url("../../images/navigation/down_arrow_small.png");
                                        }
                                    }

                                    HorizontalLayout {
                                        alignment: end;
                                        padding-right: 24px;
                                        Rectangle {
                                            background: Theme.submenu-border;
                                            width: 1px;
                                        }
                                    }
                                }
                            }

                            memory-read-mode-context-menu := ContextMenu {
                                close-policy: close-on-click-outside;
                                x: memory-read-mode-dropdown-button.x;
                                y: memory-read-mode-dropdown-button.y + memory-read-mode-dropdown-button.height;
                                Rectangle {
                                    background: Theme.background-control;
                                    border-color: Theme.submenu-border;
                                    border-width: 1px;
                                    VerticalBox {
                                        padding: 0px;
                                        spacing: 0px;
                                        Button {
                                            height: 24px;
                                            HorizontalBox {
                                                padding-left: 8px;
                                                spacing: 0px;
                                                alignment: start;
                                                Text {
                                                    vertical-alignment: center;
                                                    text: @tr("Skip");
                                                    color: Theme.foreground;
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            HorizontalBox {
                                                padding-left: 8px;
                                                spacing: 0px;
                                                alignment: start;
                                                Text {
                                                    vertical-alignment: center;
                                                    text: @tr("Interleave (fastest scan)");
                                                    color: Theme.foreground;
                                                }
                                            }
                                        }

                                        Button {
                                            height: 24px;
                                            HorizontalBox {
                                                padding-left: 8px;
                                                spacing: 0px;
                                                alignment: start;
                                                Text {
                                                    vertical-alignment: center;
                                                    text: @tr("Prior (fastest collection)");
                                                    color: Theme.foreground;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        Text {
                            vertical-alignment: center;
                            text: @tr("Memory Read Mode");
                            color: Theme.foreground;
                        }
                    }
                }
            }
        }
    }
}
