import { Theme } from "../../theme.slint";

import { PropertyViewerViewModelBindings, PropertyEntryViewData } from "../../view_model_bindings.slint";
import { PropertyEntryView } from "property_entry_view.slint";

export component PropertyViewerView inherits Rectangle {
    property <length> resizer_size: 4px;
    property <length> divider_size: 2px;
    pure function get_splitter_location() -> length {
        root.width * 0.5
    }
    content := VerticalLayout {
        padding: 0px;
        spacing: 0px;
        for index in PropertyViewerViewModelBindings.selected_properties.length: PropertyEntryView {
            property_entry: PropertyViewerViewModelBindings.selected_properties[index];
            splitter_location: root.get_splitter_location();
        }
    }

    Rectangle {
        x: root.get_splitter_location();
        y: 0;
        width: root.resizer_size;
        background: Theme.background_control;
        TouchArea {
            mouse_cursor: ew_resize;
            moved => {
                if (self.pressed && self.enabled) {
                }
            }
        }
    }
}
