import { Theme } from "../../theme.slint";

import { PropertyEntryViewData } from "../../view_model_bindings.slint";

export component PropertyEntryView inherits Rectangle {
    in property <PropertyEntryViewData> property_entry;
    in property <length> splitter_location;
    border-width: 1px;
    border-color: Theme.submenu_border;
    height: 24px;
    Text {
        x: 8px;
        horizontal-alignment: left;
        color: Theme.foreground;
        text: root.property_entry.name;
    }

    Text {
        x: splitter_location + 8px;
        horizontal-alignment: left;
        color: Theme.foreground;
        text: root.property_entry.display_value;
    }
}
