import { Theme } from "./../theme.slint";

import { Button } from "../components/buttons/button.slint";
import { IconConverter } from "../converters/icon_converter.slint";
import { IconView } from "../view_model_bindings.slint";

export component DataTypeButton inherits Button {
    in property <string> text;
    in property <IconView> icon;
    icon_converter := IconConverter { }

    HorizontalLayout {
        padding_left: 8px;
        padding_right: 8px;
        padding_top: 8px;
        padding_bottom: 8px;
        spacing: 8px;
        Image {
            width: 16px;
            height: 16px;
            horizontal_alignment: center;
            vertical_alignment: center;
            source: icon_converter.icon_view_to_image(root.icon);
        }

        Text {
            color: Theme.foreground;
            horizontal_alignment: left;
            vertical_alignment: center;
            text: root.text;
        }
    }
}
