import { Theme } from "../theme.slint";

import { ContextMenu } from "../components/context_menu/context_menu.slint";
import { Button } from "../components/buttons/button.slint";

export component ScanConstraintButton inherits Button {
    in property <string> text;
    in property <image> icon;
    HorizontalLayout {
        padding_left: 8px;
        padding_right: 8px;
        padding_top: 8px;
        padding_bottom: 8px;
        spacing: 8px;
        Image {
            width: 16px;
            height: 16px;
            horizontal_alignment: center;
            vertical_alignment: center;
            source: root.icon;
        }

        Text {
            color: Theme.foreground;
            horizontal_alignment: left;
            vertical_alignment: center;
            text: root.text;
        }
    }
}
