import { Theme } from "../../theme.slint";

import { Button } from "../../components/buttons/button.slint";
import { TextField } from "../../components/input/text_field.slint";
import { ProcessQuickSelector } from "../process_selector/process_quick_selector.slint";
import { DataTypeSelector } from "../../controls/data_type_selector.slint";
import { ScanConstraintTypeSelector } from "../../controls/scan_constraint_selector.slint";
import { DockFocusCatcher } from "../docking/drag_and_drop/dock_focus_catcher.slint";
import { DockRootViewModelBindings, ValueCollectorViewModelBindings, ScannerViewModelBindings } from "../../view_model_bindings.slint";

export component ShortcutBarView inherits Rectangle {
    property <length> bar_height: 28px;
    property <length> bar_spacing: 4px;
    property <length> bottom_padding: 4px;
    property <length> flow_break_point: 800px;
    height: bar_height + root.bottom_padding;
    background: Theme.background_primary;
    // Shortcut
    top_bar := HorizontalLayout {
        x: 0px;
        y: 0px;
        alignment: start;
        height: bar_height;
        padding_left: 4px;
        padding_right: 0px;
        padding_top: 0px;
        spacing: 4px;
        select_process_button := Button {
            height: bar_height;
            width: 36px;
            tooltip_text: @tr("Select Process");
            click_sound: "";
            clicked => {
                DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.process_selector_window.identifier);
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal_alignment: center;
                vertical_alignment: center;
                source: @image_url("../../images/app/select_process.png");
            }
        }

        process_quick_selector := ProcessQuickSelector {
            height: bar_height;
        }
    }

    DockFocusCatcher { }
}
