import { Theme } from "./../../theme.slint";

import { DockedWindowLayoutNode } from "./docked_window_layout_node.slint";
import { VerticalBox } from "std-widgets.slint";

export component DockedWindowHorizontalSplitter inherits Rectangle {
    in-out property <[DockedWindowLayoutNode]> layout;
    in-out property <[string]> children;
    // Layout is opposite to the split direction.
    VerticalLayout {
        VerticalBox {
            @children
        }
    }
}
