import { Theme } from "./../../theme.slint";
import { DockedWindowView } from "../../views/docking/docked_window_view.slint";
import { OutputView } from "../../views/output_view.slint";
import { PropertyViewerView } from "../../views/property_viewer_view.slint";
import { ProcessSelectorView } from "../../views/process_selector_view.slint";
import { ProjectExplorerView } from "../../views/project_explorer_view.slint";
import { ScanResultsView } from "../../views/scan_results_view.slint";
import { SettingsView } from "../../views/settings_view.slint";

export component DockRoot inherits Rectangle {
    background: Theme.background-primary;

    // Define size ratios for the docking layout
    // Root is split vertically between 'settings' and 'split1'
    property <float> settings_size_ratio: 0.65;
    property <float> split1_size_ratio: 1.0 - settings_size_ratio;

    // 'split1' is split horizontally between 'scan-results' and 'output'
    property <float> scan_results_size_ratio: 0.5;
    property <float> output_size_ratio: 1.0 - scan_results_size_ratio;

    // Compute widths and heights based on ratios
    property <length> settings_width: self.width * settings_size_ratio;
    property <length> split1_width: self.width - settings_width;
    property <length> scan_results_height: self.height * scan_results_size_ratio;
    property <length> output_height: self.height - scan_results_height;

    // 'settings' window
    DockedWindowView {
        x: 0;
        y: 0;
        width: root.settings_width;
        height: root.height;
        SettingsView { }
    }

    // 'scan-results' window
    DockedWindowView {
        x: root.settings_width;
        y: 0;
        width: root.split1_width;
        height: root.scan_results_height;
        ScanResultsView { }
    }

    // 'output' window
    DockedWindowView {
        x: root.settings_width;
        y: root.scan_results_height;
        width: root.split1_width;
        height: root.output_height;
        OutputView { }
    }

    // Hidden windows (collapsed)
    DockedWindowView {
        visible: false;
        width: 0;
        height: 0;
        ProcessSelectorView { }
    }

    DockedWindowView {
        visible: false;
        width: 0;
        height: 0;
        PropertyViewerView { }
    }

    DockedWindowView {
        visible: false;
        width: 0;
        height: 0;
        ProjectExplorerView { }
    }
}
