import { Theme } from "./../../theme.slint";
import { DockedWindowView } from "../../views/docking/docked_window_view.slint";
import { OutputView } from "../../views/output_view.slint";
import { PropertyViewerView } from "../../views/property_viewer_view.slint";
import { ProcessSelectorView } from "../../views/process_selector_view.slint";
import { ProjectExplorerView } from "../../views/project_explorer_view.slint";
import { ScanResultsView } from "../../views/scan_results_view.slint";
import { SettingsView } from "../../views/settings_view.slint";
import { DockedWindowViewModelBindings } from "./../../view_model_bindings.slint";

export component DockRoot inherits Rectangle {
    // width <=> DockedWindowViewModelBindings.dock_root_width;
    // height <=> DockedWindowViewModelBindings.dock_root_height;
    background: Theme.background-primary;

    // 'Settings' window
    DockedWindowView {
        docked-window-data <=> DockedWindowViewModelBindings.settings-panel;
        SettingsView { }
    }

    // 'ScanResults' window
    DockedWindowView {
        docked-window-data <=> DockedWindowViewModelBindings.scan-results-panel;
        ScanResultsView { }
    }

    // 'Output' window
    DockedWindowView {
        docked-window-data <=> DockedWindowViewModelBindings.output-panel;
        OutputView { }
    }

    // 'ProcessSelector' window
    DockedWindowView {
        docked-window-data <=> DockedWindowViewModelBindings.process-selector-panel;
        ProcessSelectorView { }
    }

    // 'PropertyViewer' window
    DockedWindowView {
        docked-window-data <=> DockedWindowViewModelBindings.property-viewer-panel;
        PropertyViewerView { }
    }

    // 'ProjectExplorer' window
    DockedWindowView {
        docked-window-data <=> DockedWindowViewModelBindings.project-explorer-panel;
        ProjectExplorerView { }
    }
}
