import { Theme } from "./../../theme.slint";

import { DockedWindowLayoutNode } from "./docked_window_layout_node.slint";
import { HorizontalBox } from "std-widgets.slint";

export component DockedWindowVerticalSplitter inherits Rectangle {
    in-out property <[DockedWindowLayoutNode]> layout;
    in-out property <[string]> children;
    // Layout is opposite to the split direction.
    HorizontalLayout {
        HorizontalBox {
            @children
        }
    }
}
