import { HorizontalBox, VerticalBox, Palette, GridBox } from "std-widgets.slint";

import { Theme } from "../theme.slint";

import { ContextMenu } from "../components/context_menu/context_menu.slint";
import { Button } from "../components/buttons/button.slint";
import { DataTypeButton } from "data_type_button.slint";
import { ManualScanViewModelBindings, DataTypeIconView } from "../view_model_bindings.slint";
import { DataTypeIconConverter } from "../converters/data_type_icon_converter.slint";

export component DataTypeSelector inherits Rectangle {
    background: Theme.background-control;
    border-color: Theme.submenu-border;
    border-width: 1px;
    width: 84px;
    data_type_icon_converter := DataTypeIconConverter { }

    data-type-button := Button {
        width: 100%;
        height: 100%;
        tooltip-text: @tr("Select a data type...");
        click-sound: "";
        clicked => {
            context-menu.show();
        }
        HorizontalLayout {
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 8px;
            padding-right: 0px;
            HorizontalBox {
                alignment: start;
                padding: 0px;
                spacing: 4px;
                VerticalLayout {
                    alignment: center;
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        source: data_type_icon_converter.data_type_source(ManualScanViewModelBindings.active_data_type.icon);
                    }
                }

                VerticalLayout {
                    alignment: center;
                    Text {
                        text: ManualScanViewModelBindings.active_data_type.data_type;
                        color: Theme.foreground;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                    }
                }
            }
        }
    }

    context-menu := ContextMenu {
        x: data-type-button.x;
        y: data-type-button.y + data-type-button.height;
        width: 192px;
        content := GridLayout {
            padding: 0px;
            spacing: 0px;
            Row {
                data-type-u8 := DataTypeButton {
                    text: @tr("u8");
                    icon: DataTypeIconView.u8;
                    tooltip-text: @tr("Data Type: u8. Size: 1 byte. Also known as an unsigned byte, or byte.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "u8", icon: self.icon };
                    }
                }

                data-type-i8 := DataTypeButton {
                    text: @tr("i8");
                    icon: DataTypeIconView.i8;
                    tooltip-text: @tr("Data Type: i8. Size: 1 byte. Also known as a signed byte, or sbyte.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "i8", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-i16 := DataTypeButton {
                    text: @tr("i16");
                    icon: DataTypeIconView.i16;
                    tooltip-text: @tr("Data Type: i16. Size: 2 bytes. Also known as a (signed) short integer, or short.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "i16", icon: self.icon };
                    }
                }

                data-type-i16be := DataTypeButton {
                    text: @tr("i16 (BE)");
                    icon: DataTypeIconView.i16be;
                    tooltip-text: @tr("Data Type: i16 (Big Endian). Size: 2 bytes. Also known as a (signed) short integer, or short. Big Endian is generally only used in certain console emulators.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "i16be", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-i32 := DataTypeButton {
                    text: @tr("i32");
                    icon: DataTypeIconView.i32;
                    tooltip-text: @tr("Data Type: i32. Size: 4 bytes. Also known as a (signed) integer, or int.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "i32", icon: self.icon };
                    }
                }

                data-type-i32be := DataTypeButton {
                    text: @tr("i32 (BE)");
                    icon: DataTypeIconView.i32be;
                    tooltip-text: @tr("Data Type: i32 (Big Endian). Size: 4 bytes. Also known as a (signed) integer, or int. Big Endian is generally only used in certain console emulators.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "i32be", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-i64 := DataTypeButton {
                    text: @tr("i64");
                    icon: DataTypeIconView.i64;
                    tooltip-text: @tr("Data Type: i64. Size: 8 bytes. Also known as a (signed) long integer, long long, or long.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "i64", icon: self.icon };
                    }
                }

                data-type-i64be := DataTypeButton {
                    text: @tr("i64 (BE)");
                    icon: DataTypeIconView.i64be;
                    tooltip-text: @tr("Data Type: i64 (Big Endian). Size: 8 bytes. Also known as a (signed) long integer, long long, or long. Big Endian is generally only used in certain console emulators.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "i64be", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-u16 := DataTypeButton {
                    text: @tr("u16");
                    icon: DataTypeIconView.u16;
                    tooltip-text: @tr("Data Type: u16. Size: 2 bytes. Also known as an unsigned short integer, unsigned short, or ushort.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "u16", icon: self.icon };
                    }
                }

                data-type-u16be := DataTypeButton {
                    text: @tr("u16 (BE)");
                    icon: DataTypeIconView.u16be;
                    tooltip-text: @tr("Data Type: u16 (Big Endian). Size: 2 bytes. Also known as an unsigned short integer, unsigned short, or ushort. Big Endian is generally only used in certain console emulators.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "u16be", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-u32 := DataTypeButton {
                    text: @tr("u32");
                    icon: DataTypeIconView.u32;
                    tooltip-text: @tr("Data Type: u32. Size: 4 bytes. Also known as an unsigned integer, unsigned int, or uint.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "u32", icon: self.icon };
                    }
                }

                data-type-u32be := DataTypeButton {
                    text: @tr("u32 (BE)");
                    icon: DataTypeIconView.u32be;
                    tooltip-text: @tr("Data Type: u32 (Big Endian). Size: 4 bytes. Also known as an unsigned integer, unsigned int, or uint. Big Endian is generally only used in certain console emulators.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "u32be", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-u64 := DataTypeButton {
                    text: @tr("u64");
                    icon: DataTypeIconView.u64;
                    tooltip-text: @tr("Data Type: u64. Size: 8 bytes. Also known as an unsigned long integer, unsigned long long, or ulong.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "u64", icon: self.icon };
                    }
                }

                data-type-u64be := DataTypeButton {
                    text: @tr("u64 (BE)");
                    icon: DataTypeIconView.u64be;
                    tooltip-text: @tr("Data Type: u64 (Big Endian). Size: 8 bytes. Also known as an unsigned long integer, unsigned long long, or ulong. Big Endian is generally only used in certain console emulators.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "u64be", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-f32 := DataTypeButton {
                    text: @tr("f32");
                    icon: DataTypeIconView.f32;
                    tooltip-text: @tr("Data Type: f32. Size: 4 bytes. Also known as a Single-precision floating point.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "f32", icon: self.icon };
                    }
                }

                data-type-f32be := DataTypeButton {
                    text: @tr("f32 (BE)");
                    icon: DataTypeIconView.f32be;
                    tooltip-text: @tr("Data Type: f32 (Big Endian). Size: 4 bytes. Also known as a Single-precision floating point. Big Endian is generally only used in certain console emulators.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "f32be", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-f64 := DataTypeButton {
                    text: @tr("f64");
                    icon: DataTypeIconView.f64;
                    tooltip-text: @tr("Data Type: f64. Size: 8 bytes. Also known as a Double-precision floating point.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "f64", icon: self.icon };
                    }
                }

                data-type-f64be := DataTypeButton {
                    text: @tr("f64 (BE)");
                    icon: DataTypeIconView.f64be;
                    tooltip-text: @tr("Data Type: f64 (Big Endian). Size: 8 bytes. Also known as a Double-precision floating point. Big Endian is generally only used in certain console emulators.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "f64be", icon: self.icon };
                    }
                }
            }

            Row {
                data-type-bytes := DataTypeButton {
                    text: @tr("u8 [ ]");
                    icon: DataTypeIconView.bytes;
                    tooltip-text: @tr("Data Type: u8[]. Size depends on the number of bytes provided. Also known as a byte[] or array of bytes. Represents a contiguous array of bytes.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "bytes", icon: self.icon };
                    }
                }

                data-type-string := DataTypeButton {
                    text: @tr("String");
                    icon: DataTypeIconView.string;
                    tooltip-text: @tr("Data Type: String. Size depends on the encoding and length of text. Represents any text.");
                    clicked => {
                        ManualScanViewModelBindings.active_data_type = { data_type: "String", icon: self.icon };
                    }
                }
            }
        }
    }
}
