import { HorizontalBox, VerticalBox, Palette, GridBox } from "std-widgets.slint";

import { Theme } from "../theme.slint";

import { Button } from "../components/buttons/button.slint";
import { DataTypeIconConverter } from "../converters/data_type_icon_converter.slint";
import { DataTypeIconView } from "../view_model_bindings.slint";

export component DataTypeButton inherits Button {
    in property <string> text;
    in property <DataTypeIconView> icon;
    data_type_icon_converter := DataTypeIconConverter { }

    HorizontalLayout {
        HorizontalBox {
            Image {
                width: 16px;
                height: 16px;
                horizontal_alignment: center;
                vertical_alignment: center;
                source: data_type_icon_converter.data_type_source(root.icon);
            }

            Text {
                color: Theme.foreground;
                horizontal_alignment: left;
                vertical_alignment: center;
                text: root.text;
            }
        }
    }
}
