import { HorizontalBox, VerticalBox, Palette, GridBox } from "std-widgets.slint";

import { Theme } from "./../theme.slint";

import { ContextMenu } from "./../components/context_menu/context_menu.slint";
import { Button } from "../components/buttons/button.slint";
import { DataTypeButton } from "data_type_button.slint";

export component DataTypeSelector inherits Rectangle {
    background: Theme.background-control;
    border-color: Theme.submenu-border;
    border-width: 1px;
    width: 96px;
    data-type-button := Button {
        width: 100%;
        height: 100%;
        tooltip-text: @tr("Select a data type...");
        click-sound: "";
        clicked => {
            context-menu.show();
        }
        HorizontalLayout {
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 8px;
            padding-right: 0px;
            HorizontalBox {
                alignment: start;
                padding: 0px;
                spacing: 4px;
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: @tr("Data Type");
                        color: Theme.foreground;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                    }
                }

                VerticalLayout {
                    alignment: center;
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        source: @image-url("./../images/data_types/blue_blocks_4.png");
                    }
                }
            }
        }
    }

    context-menu := ContextMenu {
        x: data-type-button.x;
        y: data-type-button.y + data-type-button.height;
        width: 192px;
        content := GridLayout {
            padding: 0px;
            spacing: 0px;
            Row {
                data-type-u8 := DataTypeButton {
                    text: @tr("u8");
                    icon: @image-url("./../images/data_types/purple_blocks_1.png");
                    tooltip-text: @tr("Data Type: u8. Size: 1 byte. Also known as an unsigned byte, or byte.");
                }

                data-type-i8 := DataTypeButton {
                    text: @tr("i8");
                    icon: @image-url("./../images/data_types/blue_blocks_1.png");
                    tooltip-text: @tr("Data Type: i8. Size: 1 byte. Also known as a signed byte, or sbyte.");
                }
            }

            Row {
                data-type-i16 := DataTypeButton {
                    text: @tr("i16");
                    icon: @image-url("./../images/data_types/blue_blocks_2.png");
                    tooltip-text: @tr("Data Type: i16. Size: 2 bytes. Also known as a (signed) short integer, or short.");
                }

                data-type-i16be := DataTypeButton {
                    text: @tr("i16 (BE)");
                    icon: @image-url("./../images/data_types/blue_blocks_2.png");
                    tooltip-text: @tr("Data Type: i16 (Big Endian). Size: 2 bytes. Also known as a (signed) short integer, or short. Big Endian is generally only used in certain console emulators.");
                }
            }

            Row {
                data-type-i32 := DataTypeButton {
                    text: @tr("i32");
                    icon: @image-url("./../images/data_types/blue_blocks_4.png");
                    tooltip-text: @tr("Data Type: i32. Size: 4 bytes. Also known as a (signed) integer, or int.");
                }

                data-type-i32be := DataTypeButton {
                    text: @tr("i32 (BE)");
                    icon: @image-url("./../images/data_types/blue_blocks_4.png");
                    tooltip-text: @tr("Data Type: i32 (Big Endian). Size: 4 bytes. Also known as a (signed) integer, or int. Big Endian is generally only used in certain console emulators.");
                }
            }

            Row {
                data-type-i64 := DataTypeButton {
                    text: @tr("i64");
                    icon: @image-url("./../images/data_types/blue_blocks_8.png");
                    tooltip-text: @tr("Data Type: i64. Size: 8 bytes. Also known as a (signed) long integer, long long, or long.");
                }

                data-type-i64be := DataTypeButton {
                    text: @tr("i64 (BE)");
                    icon: @image-url("./../images/data_types/blue_blocks_8.png");
                    tooltip-text: @tr("Data Type: i64 (Big Endian). Size: 8 bytes. Also known as a (signed) long integer, long long, or long. Big Endian is generally only used in certain console emulators.");
                }
            }

            Row {
                data-type-u16 := DataTypeButton {
                    text: @tr("u16");
                    icon: @image-url("./../images/data_types/purple_blocks_2.png");
                    tooltip-text: @tr("Data Type: u16. Size: 2 bytes. Also known as an unsigned short integer, unsigned short, or ushort.");
                }

                data-type-u16be := DataTypeButton {
                    text: @tr("u16 (BE)");
                    icon: @image-url("./../images/data_types/purple_blocks_2.png");
                    tooltip-text: @tr("Data Type: u16 (Big Endian). Size: 2 bytes. Also known as an unsigned short integer, unsigned short, or ushort. Big Endian is generally only used in certain console emulators.");
                }
            }

            Row {
                data-type-u32 := DataTypeButton {
                    text: @tr("u32");
                    icon: @image-url("./../images/data_types/purple_blocks_4.png");
                    tooltip-text: @tr("Data Type: u32. Size: 4 bytes. Also known as an unsigned integer, unsigned int, or uint.");
                }

                data-type-u32be := DataTypeButton {
                    text: @tr("u32 (BE)");
                    icon: @image-url("./../images/data_types/purple_blocks_4.png");
                    tooltip-text: @tr("Data Type: u32 (Big Endian). Size: 4 bytes. Also known as an unsigned integer, unsigned int, or uint. Big Endian is generally only used in certain console emulators.");
                }
            }

            Row {
                data-type-u64 := DataTypeButton {
                    text: @tr("u64");
                    icon: @image-url("./../images/data_types/purple_blocks_8.png");
                    tooltip-text: @tr("Data Type: u64. Size: 8 bytes. Also known as an unsigned long integer, unsigned long long, or ulong.");
                }

                data-type-u64be := DataTypeButton {
                    text: @tr("u64 (BE)");
                    icon: @image-url("./../images/data_types/purple_blocks_8.png");
                    tooltip-text: @tr("Data Type: u64 (Big Endian). Size: 8 bytes. Also known as an unsigned long integer, unsigned long long, or ulong. Big Endian is generally only used in certain console emulators.");
                }
            }

            Row {
                data-type-f32 := DataTypeButton {
                    text: @tr("f32");
                    icon: @image-url("./../images/data_types/orange_blocks_4.png");
                    tooltip-text: @tr("Data Type: f32. Size: 4 bytes. Also known as a Single-precision floating point.");
                }

                data-type-f32be := DataTypeButton {
                    text: @tr("f32 (BE)");
                    icon: @image-url("./../images/data_types/orange_blocks_4.png");
                    tooltip-text: @tr("Data Type: f32 (Big Endian). Size: 4 bytes. Also known as a Single-precision floating point. Big Endian is generally only used in certain console emulators.");
                }
            }

            Row {
                data-type-f64 := DataTypeButton {
                    text: @tr("f64");
                    icon: @image-url("./../images/data_types/orange_blocks_8.png");
                    tooltip-text: @tr("Data Type: f64. Size: 8 bytes. Also known as a Double-precision floating point.");
                }

                data-type-f64be := DataTypeButton {
                    text: @tr("f64 (BE)");
                    icon: @image-url("./../images/data_types/orange_blocks_8.png");
                    tooltip-text: @tr("Data Type: f64 (Big Endian). Size: 8 bytes. Also known as a Double-precision floating point. Big Endian is generally only used in certain console emulators.");
                }
            }

            Row {
                data-type-bytes := DataTypeButton {
                    // TODO: These should be purple
                    icon: @image-url("./../images/data_types/blue_blocks_array.png");
                    text: @tr("u8 [ ]");
                    tooltip-text: @tr("Data Type: u8[]. Size depends on the number of bytes provided. Also known as a byte[] or array of bytes. Represents a contiguous array of bytes.");
                }

                data-type-string := DataTypeButton {
                    // TODO: Find your own damn icon
                    icon: @image-url("./../images/projects/static_type.png");
                    text: @tr("string");
                    tooltip-text: @tr("Data Type: String. Size depends on the encoding and length of text. Represents any text.");
                }
            }
        }
    }
}
