import { HorizontalBox, VerticalBox, Palette, GridBox } from "std-widgets.slint";

import { Theme } from "../theme.slint";

import { ContextMenu } from "../components/context_menu/context_menu.slint";
import { Button } from "../components/buttons/button.slint";
import { ScanConstraintButton } from "scan_constraint_button.slint";
import { ScanConstraintTypeIconConverter } from "../converters/scan_constraint_type_icon_converter.slint";
import { ScannerViewModelBindings, ScanConstraintTypeView } from "../view_model_bindings.slint";

export component ScanConstraintTypeSelector inherits Rectangle {
    background: Theme.background_control;
    border_color: Theme.submenu_border;
    border_width: 1px;
    width: 36px;
    scan_constraint_type_icon_converter := ScanConstraintTypeIconConverter { }

    select_scan_constraint_button := Button {
        width: 100%;
        height: 100%;
        tooltip_text: @tr("Select a scan type...");
        click_sound: "";
        clicked => {
            context_menu.show();
        }
        Image {
            width: 16px;
            height: 16px;
            horizontal_alignment: center;
            vertical_alignment: center;
            source: scan_constraint_type_icon_converter.scan_constraint_type_source(ScannerViewModelBindings.active_scan_type);
        }
    }

    context_menu := ContextMenu {
        x: select_scan_constraint_button.x;
        y: select_scan_constraint_button.y + select_scan_constraint_button.height;
        content := Rectangle {
            border_color: Theme.submenu_border;
            border_width: 2px;
            grid_layout := GridLayout {
                padding: parent.border_width;
                spacing: 0px;
                Rectangle {
                    colspan: 2;
                    background: Theme.background_panel;
                    HorizontalLayout {
                        alignment: start;
                        padding: 2px;
                        padding_left: 8px;
                        Text {
                            text: @tr("Relative");
                            color: Theme.foreground;
                            font_size: Theme.font_size_h5;
                            horizontal_alignment: center;
                        }
                    }
                }

                Row {
                    constraint_changed := ScanConstraintButton {
                        text: @tr("Changed");
                        icon: @image_url("../images/scans/scan_relative_changed.png");
                        tooltip_text: "Scan for values that have changed since the previous scan.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.changed;
                        }
                    }

                    constraint_unchanged := ScanConstraintButton {
                        text: @tr("Unchanged");
                        icon: @image_url("../images/scans/scan_relative_unchanged.png");
                        tooltip_text: "Scan for values that have not changed since the previous scan.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.unchanged;
                        }
                    }
                }

                Row {
                    constraint_increased := ScanConstraintButton {
                        text: @tr("Increased");
                        icon: @image_url("../images/scans/scan_relative_increased.png");
                        tooltip_text: "Scan for values that have increased since the previous scan.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.increased;
                        }
                    }

                    constraint_decreased := ScanConstraintButton {
                        text: @tr("Decreased");
                        icon: @image_url("../images/scans/scan_relative_decreased.png");
                        tooltip_text: "Scan for values that have decreased since the previous scan.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.decreased;
                        }
                    }
                }

                Rectangle {
                    colspan: 2;
                    background: Theme.background_panel;
                    HorizontalLayout {
                        alignment: start;
                        padding: 2px;
                        padding_left: 8px;
                        Text {
                            text: @tr("Immediate");
                            color: Theme.foreground;
                            font_size: Theme.font_size_h5;
                            horizontal_alignment: center;
                        }
                    }
                }

                Row {
                    constraint_equal := ScanConstraintButton {
                        text: @tr("Equal");
                        icon: @image_url("../images/scans/scan_immediate_equal.png");
                        tooltip_text: "Scan for values that are equal to the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.equal;
                        }
                    }

                    constraint_not_equal := ScanConstraintButton {
                        text: @tr("Not Equal");
                        icon: @image_url("../images/scans/scan_immediate_not_equal.png");
                        tooltip_text: "Scan for values that are not equal to the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.not_equal;
                        }
                    }
                }

                Row {
                    constraint_greater_than := ScanConstraintButton {
                        text: @tr("Greater Than");
                        icon: @image_url("../images/scans/scan_immediate_greater_than.png");
                        tooltip_text: "Scan for values that are greater than the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.greater_than;
                        }
                    }

                    constraint_greater_than_or_equal := ScanConstraintButton {
                        text: @tr("Greater Than or Equal to");
                        icon: @image_url("../images/scans/scan_immediate_greater_than_or_equal.png");
                        tooltip_text: "Scan for values that are greater than or equal to the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.greater_than_or_equal;
                        }
                    }
                }

                Row {
                    constraint_less_than := ScanConstraintButton {
                        text: @tr("Less Than");
                        icon: @image_url("../images/scans/scan_immediate_less_than.png");
                        tooltip_text: "Scan for values that are less than the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.less_than;
                        }
                    }

                    constraint_less_than_or_equal := ScanConstraintButton {
                        text: @tr("Less Than or Equal to");
                        icon: @image_url("../images/scans/scan_immediate_less_than_or_equal.png");
                        tooltip_text: "Scan for values that are less than or equal to the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.less_than_or_equal;
                        }
                    }
                }

                Rectangle {
                    colspan: 2;
                    background: Theme.background_panel;
                    HorizontalLayout {
                        alignment: start;
                        padding: 2px;
                        padding_left: 8px;
                        Text {
                            text: @tr("Delta");
                            color: Theme.foreground;
                            font_size: Theme.font_size_h5;
                            horizontal_alignment: center;
                        }
                    }
                }

                Row {
                    constraint_increased_by_x := ScanConstraintButton {
                        text: @tr("Increased by x");
                        icon: @image_url("../images/scans/scan_delta_increased_by_x.png");
                        tooltip_text: "Scan for values that have increased by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.increased_by_x;
                        }
                    }

                    constraint_decreased_by_x := ScanConstraintButton {
                        text: @tr("Decreased by x");
                        icon: @image_url("../images/scans/scan_delta_decreased_by_x.png");
                        tooltip_text: "Scan for values that have decreased by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.decreased_by_x;
                        }
                    }
                }

                Row {
                    constraint_multiplied_by_x := ScanConstraintButton {
                        text: @tr("Multiplied by x");
                        icon: @image_url("../images/scans/scan_delta_multiplied_by_x.png");
                        tooltip_text: "Scan for values that have been multiplied by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.multiplied_by_x;
                        }
                    }

                    constraint_divided_by_x := ScanConstraintButton {
                        text: @tr("Divided by x");
                        icon: @image_url("../images/scans/scan_delta_divided_by_x.png");
                        tooltip_text: "Scan for values that have been divided by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.divided_by_x;
                        }
                    }
                }

                Row {
                    constraint_modulo_by_x := ScanConstraintButton {
                        text: @tr("Modulo by x");
                        icon: @image_url("../images/scans/scan_delta_modulo_by_x.png");
                        tooltip_text: "Scan for the remainder of values that have been divided by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.modulo_by_x;
                        }
                    }
                }

                Rectangle {
                    colspan: 2;
                    background: Theme.background_panel;
                    HorizontalLayout {
                        alignment: start;
                        padding: 2px;
                        padding_left: 8px;
                        Text {
                            text: @tr("Binary");
                            color: Theme.foreground;
                            font_size: Theme.font_size_h5;
                            horizontal_alignment: center;
                        }
                    }
                }

                Row {
                    constraint_shift_left_by_x := ScanConstraintButton {
                        text: @tr("Shifted left by x");
                        icon: @image_url("../images/scans/scan_delta_shift_left_by_x.png");
                        tooltip_text: "Scan for values that have been shifted left by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.shift_left_by_x;
                        }
                    }

                    constraint_shift_right_by_x := ScanConstraintButton {
                        text: @tr("Shifted right by x");
                        icon: @image_url("../images/scans/scan_delta_shift_right_by_x.png");
                        tooltip_text: "Scan for values that have been shifted right by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.shift_right_by_x;
                        }
                    }
                }

                Row {
                    constraint_logical_and_by_x := ScanConstraintButton {
                        text: @tr("Logical AND'd by x");
                        icon: @image_url("../images/scans/scan_delta_logical_and_by_x.png");
                        tooltip_text: "Scan for values that have been logical AND'd by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.logical_and_by_x;
                        }
                    }

                    constraint_logical_or_by_x := ScanConstraintButton {
                        text: @tr("Logical OR'd by x");
                        icon: @image_url("../images/scans/scan_delta_logical_or_by_x.png");
                        tooltip_text: "Scan for values that have been logical OR'd by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.logical_or_by_x;
                        }
                    }
                }

                Row {
                    constraint_logical_xor_by_x := ScanConstraintButton {
                        text: @tr("Logical XOR'd by x");
                        icon: @image_url("../images/scans/scan_delta_logical_xor_by_x.png");
                        tooltip_text: "Scan for values that have been logical XOR'd by the entered value.";
                        clicked => {
                            ScannerViewModelBindings.active_scan_type = ScanConstraintTypeView.logical_xor_by_x;
                        }
                    }
                }
            }
        }
    }
}
