import { VerticalBox } from "std-widgets.slint";

import { Theme } from "./../../theme.slint";

import { DockRootViewModelBindings, DockedWindowViewData } from "./../../view_model_bindings.slint";
import { DockedWindowTitleBarView } from "docked_window_title_bar_view.slint";
import { DockedWindowFooter } from "docked_window_footer.slint";
import { DockedWindowDropArea } from "docked_window_drop_area.slint";
import { DockedWindowSplitters } from "docked_window_splitters.slint";

export component DockedWindowView inherits Rectangle {
    in-out property <DockedWindowViewData> docked-window-data;
    property <length> resize-padding: 8px;
    x: root.docked-window-data.position-x;
    y: root.docked-window-data.position-y;
    width: root.docked-window-data.width;
    height: root.docked-window-data.height;
    visible: root.docked-window-data.is-visible;
    background: Theme.background-control;
    VerticalLayout {
        x: resize-padding;
        y: resize-padding;
        width: root.docked-window-data.width - resize-padding * 2;
        height: root.docked-window-data.height - resize-padding * 2;
        spacing: 0px;
        padding: 0px;
        VerticalBox {
            padding: 0px;
            spacing: 0px;
            DockedWindowTitleBarView {
                docked-window-data <=> root.docked-window-data;
            }

            // Main content area
            Rectangle {
                background: Theme.background-panel;
                border-color: Theme.submenu-border;
                border-radius: 2px;
                border-width: 1px;
                @children
            }

            DockedWindowFooter {
                docked-window-data <=> root.docked-window-data;
            }
        }
    }

    // Drop Area
    drop-area := DockedWindowDropArea {
        docked-window-data <=> root.docked-window-data;
        resize-padding <=> root.resize-padding;
        visible: DockRootViewModelBindings.active-dragged-window-id != "" && DockRootViewModelBindings.active-dragged-window-id != root.docked-window-data.active-tab-id && DockRootViewModelBindings.active-dragged-window-id != root.docked-window-data.identifier;
    }

    // Splitters
    splitters := DockedWindowSplitters {
        docked-window-data <=> root.docked-window-data;
        resize-padding <=> root.resize-padding;
    }
}
