import { Theme } from "../../theme.slint";
import { WindowViewModelBindings } from "./../../view_model_bindings.slint";
import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";
import { Button } from "../../components/buttons/button.slint";

export component DockedWindowTitleBarView inherits Rectangle {
    in property <string> title <=> title.text;
    background: Theme.background-primary;
    height: 24px;
    title-drag := TouchArea {
        double-clicked => {
            if (self.pressed && self.enabled) {
                WindowViewModelBindings.double-clicked();
            }
        }
        moved => {
            if (self.pressed && self.enabled) {
                WindowViewModelBindings.drag((title-drag.mouse-x - title-drag.pressed-x) / 1px, (title-drag.mouse-y - title-drag.pressed-y) / 1px);
            }
        }
    }

    HorizontalLayout {
        padding: 0px;
        // Title
        VerticalLayout {
            alignment: center;
            padding-top: 0px;
            padding-bottom: 0px;
            padding-left: 8px;
            padding-right: 0px;
            title := Text {
                text: "<Docked window title bar>";
                vertical-alignment: center;
                color: Theme.foreground;
            }
        }

        HorizontalBox {
            alignment: end;
            padding: 0px;
            spacing: 0px;
            close-button := Button {
                width: 36px;
                tooltip-text: @tr("Close");
                click-sound: "";
                clicked => {
                    WindowViewModelBindings.close();
                }
                Image {
                    width: 16px;
                    height: 16px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    source: @image-url("../../images/app/close.png");
                }
            }
        }
    }
}
