import { Theme } from "./../../theme.slint";
import { DockedWindowViewModelBindings, DockedWindowData } from "./../../view_model_bindings.slint";

export component DockedWindowView inherits Rectangle {
    in-out property <DockedWindowData> docked-window-data;
    property <length> resize-padding: 2px;
    background: Theme.background-control;

    // Left border splitter
    Rectangle {
        x: 0;
        y: 0;
        width: resize-padding;
        height: root.docked-window-data.height;
        background: red;
        TouchArea {
            mouse-cursor: ew-resize;
            moved => {
                if (self.pressed && self.enabled) {
                    DockedWindowViewModelBindings.drag-left(
                        root.docked-window-data.identifier,
                        (self.mouse-x - self.pressed-x) / 1px,
                        (self.mouse-y - self.pressed-y) / 1px);
                }
            }
        }
    }

    // Right border splitter
    Rectangle {
        x: root.docked-window-data.width - resize-padding;
        y: 0;
        width: resize-padding;
        height: root.docked-window-data.height;
        background: green;
        TouchArea {
            mouse-cursor: ew-resize;
            moved => {
                if (self.pressed && self.enabled) {
                    DockedWindowViewModelBindings.drag-right(
                        root.docked-window-data.identifier,
                        (self.mouse-x - self.pressed-x) / 1px,
                        (self.mouse-y - self.pressed-y) / 1px);
                }
            }
        }
    }

    // Top border splitter
    Rectangle {
        x: 0;
        y: 0;
        width: root.docked-window-data.width;
        height: resize-padding;
        background: blue;
        TouchArea {
            mouse-cursor: ns-resize;
            moved => {
                if (self.pressed && self.enabled) {
                    DockedWindowViewModelBindings.drag-top(
                        root.docked-window-data.identifier,
                        (self.mouse-x - self.pressed-x) / 1px,
                        (self.mouse-y - self.pressed-y) / 1px);
                }
            }
        }
    }

    // Bottom border splitter
    Rectangle {
        x: 0;
        y: root.docked-window-data.height - resize-padding;
        width: root.docked-window-data.width;
        height: resize-padding;
        background: yellow;
        TouchArea {
            mouse-cursor: ns-resize;
            moved => {
                if (self.pressed && self.enabled) {
                    DockedWindowViewModelBindings.drag-bottom(
                        root.docked-window-data.identifier,
                        (self.mouse-x - self.pressed-x) / 1px,
                        (self.mouse-y - self.pressed-y) / 1px);
                }
            }
        }
    }

    // Main content area
    Rectangle {
        background: Theme.background-panel;
        border-color: Theme.submenu-border;
        border-radius: 2px;
        border-width: 1px;
        x: resize-padding;
        y: resize-padding;
        width: root.docked-window-data.width - resize-padding * 2;
        height: root.docked-window-data.height - resize-padding * 2;
        @children
    }
}
