import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { DockedWindowViewModelBindings, DockedWindowViewData } from "./../../view_model_bindings.slint";
import { Button } from "../../components/buttons/button.slint";

export component DockedWindowFooter inherits Rectangle {
    in-out property <DockedWindowViewData> docked-window-data;
    visible: docked-window-data.tabs.length > 0;
    background: Theme.background-primary;
    height: docked-window-data.tabs.length > 0 ? 24px : 0px;
    HorizontalLayout {
        padding: 0px;
        HorizontalBox {
            alignment: start;
            padding: 0px;
            spacing: 0px;
            for tab in docked-window-data.tabs: Button {
                height: 24px;
                clicked => {
                }
                HorizontalLayout {
                    alignment: start;
                    padding-left: 8px;
                    padding-right: 8px;
                    Text {
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        text: tab;
                        color: Theme.foreground;
                    }
                }
            }
        }
    }
}
