import { Theme } from "./../../theme.slint";

import { DockRootViewModelBindings } from "../../view_model_bindings.slint";

export component DockFocusCatcher inherits Rectangle {
    background: #b124a73c;
    TouchArea {
        enabled: DockRootViewModelBindings.active-dragged-window-id != "";
        pointer-event(event) => {
            if (event.kind == PointerEventKind.up) {
                DockRootViewModelBindings.active-dragged-window-id = "";
                DockRootViewModelBindings.is-dragging-window = false;
            }
        }
    }
}
