import { HorizontalBox, VerticalBox, Palette, Button } from "std-widgets.slint";
import {Theme} from "../../theme.slint";

export global PanelTitleBarAdapter {
    callback close();
    callback maximize();
    callback minimize();
    callback drag();
}

export component PanelTitleBarView inherits Rectangle {
    in property <[string]> model: [];
    in property <string> title <=> title.text;
    height: 64px;
    accessible-role: tab;
    Rectangle {
        background: Palette.background.darker(0.2);
    }

    VerticalLayout {
        padding: 0;
        // Title Bar
        Rectangle {
            height: 38px;
            background: Theme.background;
            HorizontalLayout {
                padding-right: 8px;
                padding-left: 8px;
                Image {
                    horizontal-alignment: left;
                    source: @image-url("../../images/app/app_icon.png");
                }

                title := Text {
                    padding-left: 8px;
                    font-size: 12pt;
                    color: Theme.short-round;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    TouchArea {
                        moved => {
                            if (self.pressed && self.enabled) {
                                PanelTitleBarAdapter.drag();
                            }
                        }
                    }
                }

                Rectangle {
                    y: parent.height / 2 - self.height / 2;
                    width: parent.height * 0.75;
                    height: parent.height * 0.75;
                    minBtn-ta := TouchArea {
                        clicked => {
                            PanelTitleBarAdapter.minimize()
                        }
                    }

                    Image {
                        source: @image-url("../../images/app/minimize.png");
                        animate colorize {
                            duration: 50ms;
                            easing: ease-in-out;
                        }
                        states [
                            hvr when minBtn-ta.has-hover: {
                                colorize: Theme.accent;
                            }
                            nthvr when !minBtn-ta.has-hover: {
                                colorize: Theme.background-lightest;
                            }
                        ]
                    }
                }

                Rectangle {
                    y: parent.height / 2 - self.height / 2;
                    width: parent.height * 0.75;
                    height: parent.height * 0.75;
                    maxBtn-ta := TouchArea {
                        clicked => {
                            PanelTitleBarAdapter.maximize()
                        }
                    }

                    Image {
                        source: @image-url("../../images/app/maximize.png");
                        animate colorize {
                            duration: 50ms;
                            easing: ease-in-out;
                        }
                        states [
                            hvr when maxBtn-ta.has-hover: {
                                colorize: Theme.accent;
                            }
                            nthvr when !maxBtn-ta.has-hover: {
                                colorize: Theme.background-lightest;
                            }
                        ]
                    }
                }

                Rectangle {
                    y: parent.height / 2 - self.height / 2;
                    width: parent.height * 0.75;
                    height: parent.height * 0.75;
                    closeBtn-ta := TouchArea {
                        clicked => {
                            PanelTitleBarAdapter.close()
                        }
                    }

                    Image {
                        source: @image-url("../../images/app/close.png");
                        animate colorize {
                            duration: 50ms;
                            easing: ease-in-out;
                        }
                        states [
                            hvr when closeBtn-ta.has-hover: {
                                colorize: Theme.accent;
                            }
                            nthvr when !closeBtn-ta.has-hover: {
                                colorize: Theme.background-lightest;
                            }
                        ]
                    }
                }
            }
        }

        Rectangle {
            background: Theme.background;
            @children
        }
    }
}
