import { Theme } from "../../theme.slint";
import { WindowViewModelBindings } from "./../../view_model_bindings.slint";

import { HorizontalBox, VerticalBox, Palette, Button } from "std-widgets.slint";
import { IconButton } from "../../components/buttons/icon_button.slint";

export component PanelTitleBarView inherits Rectangle {
    in property <string> title <=> title.text;
    height: 32px;
    Rectangle {
        border-top-left-radius: 8px;
        border-top-right-radius: 8px;
        background: Theme.background-primary;
        title-drag := TouchArea {
            double-clicked => {
                if (self.pressed && self.enabled) {
                    WindowViewModelBindings.double-clicked();
                }
            }
            moved => {
                if (self.pressed && self.enabled) {
                    WindowViewModelBindings.drag((title-drag.mouse-x - title-drag.pressed-x) / 1px, (title-drag.mouse-y - title-drag.pressed-y) / 1px);
                }
            }
        }

        HorizontalLayout {
            padding-top: 4px;
            padding-left: 8px;
            spacing: 8px;
            app_icon := Image {
                source: @image-url("../../images/app/app_icon.png");
                width: 24px;
            }

            title := Text {
                vertical-alignment: center;
                color: Theme.foreground;
            }

            minimize-button := IconButton {
                icon: @image-url("../../images/app/minimize.png");
                tooltip-text: @tr("Minimize");
                width: 24px;
                clicked => {
                    WindowViewModelBindings.minimize()
                }
            }

            maximize-button := IconButton {
                icon: @image-url("../../images/app/maximize.png");
                tooltip-text: @tr("Maximize");
                width: 24px;
                clicked => {
                    WindowViewModelBindings.maximize()
                }
            }

            close-button := IconButton {
                icon: @image-url("../../images/app/close.png");
                tooltip-text: @tr("Close");
                width: 24px;
                clicked => {
                    WindowViewModelBindings.close()
                }
            }
        }
    }
}
