[package]
name = "squalr-plugin-debuggers-native"
version = "0.5.0"
authors = ["Zachary Canann"]
edition = "2024"

[dependencies]
log = "0.4.29"
squalr-engine-api = { path = "../../squalr-engine-api" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_System_Diagnostics_Debug_Extensions"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2.180"
mach2 = "0.4.3"

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
iced-x86 = { version = "1.21.0", default-features = false, features = ["std", "decoder"] }
libc = "0.2.180"

[target.'cfg(all(target_os = "android", target_arch = "aarch64"))'.dependencies]
libc = "0.2.180"
