import { ScrollView } from "std-widgets.slint";

import { Theme } from "../../../theme.slint";

import { ProjectExplorerViewModelBindings } from "../../../view_model_bindings.slint";
import { Button } from "../../../components/buttons/button.slint";
import { BevelButton } from "../../../components/buttons/bevel_button.slint";
import { ProjectEntry } from "project_entry.slint";

export component ProjectSelectorTab inherits Rectangle {
    VerticalLayout {
        padding: 0px;
        spacing: 0px;
        Rectangle {
            background: Theme.background_control;
            HorizontalLayout {
                padding: 2px;
                spacing: 4px;
                new_project_button := Button {
                    height: 24px;
                    width: 36px;
                    tooltip_text: @tr("New Project");
                    click_sound: "";
                    clicked => {
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        source: @image_url("../../../images/scans/scan_new.png");
                    }
                }

                refresh_button := Button {
                    height: 24px;
                    width: 36px;
                    tooltip_text: @tr("Refresh");
                    click_sound: "";
                    clicked => {
                        ProjectExplorerViewModelBindings.refresh_project_list();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        source: @image_url("../../../images/navigation/redo.png");
                    }
                }
            }
        }

        ScrollView {
            content := VerticalLayout {
                padding: 0px;
                spacing: 0px;
                for process_entry in ProjectExplorerViewModelBindings.projects: ProjectEntry {
                    process_view_data: process_entry;
                    on_click => {
                    }
                }
            }
        }
    }
}
