import { Theme } from "../../../theme.slint";

import { ProjectExplorerViewModelBindings, ProjectViewData } from "../../../view_model_bindings.slint";
import { ContextMenu } from "../../../components/context_menu/context_menu.slint";
import { Button } from "../../../components/buttons/button.slint";

export component ProjectEntry inherits Button {
    in property <ProjectViewData> process_view_data;
    callback on_click();
    clicked => {
        root.on_click();
    }
    HorizontalLayout {
        spacing: 8px;
        Image {
            width: 16px;
            height: 16px;
            horizontal_alignment: center;
            vertical_alignment: center;
        }

        Text {
            color: Theme.foreground;
            horizontal_alignment: left;
            vertical_alignment: center;
            text: process_view_data.name;
        }
    }
}
