import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { Button } from "../../components/buttons/button.slint";
import { TextField } from "../../components/input/text_field.slint";
import { ProcessQuickSelector } from "../process_selector/process_quick_selector.slint";
import { DataTypeSelector } from "../../controls/data_type_selector.slint";
import { ScanConstraintTypeSelector } from "../../controls/scan_constraint_selector.slint";
import { DockFocusCatcher } from "../docking/drag_and_drop/dock_focus_catcher.slint";
import { DataValueBox } from "../../components/data_value_box/data_value_box.slint";
import { DataTypeView, ValueCollectorViewModelBindings, ScannerViewModelBindings } from "../../view_model_bindings.slint";

export component ScanBarView inherits Rectangle {
    property <length> bar-height: 28px;
    property <length> bar-spacing: 4px;
    property <length> bottom-padding: 4px;
    property <length> flow-break-point: 800px;
    height: bar-height + root.bottom-padding;
    background: Theme.background-primary;
    // Shortcut
    top-bar := HorizontalBox {
        x: 0px;
        y: 0px;
        alignment: start;
        height: bar-height;
        padding-left: 4px;
        padding-right: 0px;
        padding-top: 0px;
        spacing: 4px;
        new-scan-button := Button {
            height: bar-height;
            width: 36px;
            tooltip-text: @tr("Reset Scan");
            click-sound: "";
            clicked => {
                ScannerViewModelBindings.reset_scan();
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: @image-url("../../images/scans/scan_new.png");
            }
        }

        collect-values-button := Button {
            height: bar-height;
            width: 36px;
            tooltip-text: @tr("Collect Values");
            click-sound: "";
            clicked => {
                ValueCollectorViewModelBindings.collect_values();
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: @image-url("../../images/scans/scan_collect_values.png");
            }
        }

        scan-constraint-selector := ScanConstraintTypeSelector {
            height: bar-height;
        }

        scan-value := DataValueBox {
            data_type <=> ScannerViewModelBindings.active_data_type;
            height: bar-height;
            text-padding-top: 0px;
            text-padding-bottom: 0px;
            width: 192px;
            preview-text: @tr("Enter a scan value...");
        }

        data-type-selector := DataTypeSelector {
            height: bar-height;
        }

        start-scan-button := Button {
            height: bar-height;
            width: 36px;
            tooltip-text: @tr("Start Scan");
            click-sound: "";
            clicked => {
                ScannerViewModelBindings.start_scan(ScannerViewModelBindings.active_data_type, ScannerViewModelBindings.active_scan_type, scan-value.get_value_text());
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: @image-url("../../images/navigation/right_arrow.png");
            }
        }
    }

    DockFocusCatcher { }
}
