import { Theme } from "./../../theme.slint";

import { DockedWindowView } from "../../views/docking/docked_window_view.slint";
import { OutputView } from "../../views/output/output_view.slint";
import { PropertyViewerView } from "../../views/property_viewer/property_viewer_view.slint";
import { ProcessSelectorView } from "../../views/process_selector/process_selector_view.slint";
import { ProjectExplorerView } from "../../views/project_explorer/project_explorer_view.slint";
import { ScanResultsView } from "../../views/scanning/scan_results_view.slint";
import { SettingsView } from "../../views/settings/settings_view.slint";
import { DockRootViewModelBindings } from "./../../view_model_bindings.slint";

export component DockRoot inherits Rectangle {
    // JIRA: These fail to fire until the window is done being dragged. It would be nice if we had real time.
    changed width => {
        DockRootViewModelBindings.update_dock_root_width(root.width);
    }
    changed height => {
        DockRootViewModelBindings.update_dock_root_height(root.height);
    }
    background: Theme.background_primary;
    init => {
        // These may no longer be needed.
        DockRootViewModelBindings.initial_dock_root_width = root.width;
        DockRootViewModelBindings.initial_dock_root_height = root.height;
    }

    // 'Settings' window
    settings_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.settings_window;
        SettingsView { }
    }

    // 'ScanResults' window
    scan_results_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.scan_results_window;
        ScanResultsView { }
    }

    // 'Output' window
    output_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.output_window;
        OutputView { }
    }

    // 'ProcessSelector' window
    process_selector_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.process_selector_window;
        ProcessSelectorView { }
    }

    // 'PropertyViewer' window
    property_viewer_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.property_viewer_window;
        PropertyViewerView { }
    }

    // 'ProjectExplorer' window
    project_explorer_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.project_explorer_window;
        ProjectExplorerView { }
    }
}
