import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { DockRootViewModelBindings, DockedWindowViewData } from "../../view_model_bindings.slint";
import { Button } from "../../components/buttons/button.slint";

export component DockedWindowTitleBarView inherits Rectangle {
    in_out property <DockedWindowViewData> docked_window_data;
    background: docked_window_data.identifier == DockRootViewModelBindings.active_dragged_window_id ? Theme.selected_border : Theme.background_primary;
    height: 24px;
    title_drag := TouchArea {
        enabled: !DockRootViewModelBindings.is_dragging_window;
        moved => {
            if (self.pressed && self.enabled) {
                // Begin dragging this window for a potential redock operation.
                DockRootViewModelBindings.active_dragged_window_id = docked_window_data.identifier;

                // Disable ourself to relinquish control over the mouse, allowing hit (and thus drop) detection on other elements.
                DockRootViewModelBindings.is_dragging_window = true;
            }
        }
    }

    HorizontalLayout {
        padding: 0px;
        // Title
        VerticalLayout {
            alignment: center;
            padding_top: 0px;
            padding_bottom: 0px;
            padding_left: 8px;
            padding_right: 0px;
            title := Text {
                text: DockRootViewModelBindings.get_tab_text(docked_window_data.identifier);
                vertical_alignment: center;
                color: Theme.foreground;
            }
        }

        HorizontalBox {
            alignment: end;
            padding: 0px;
            spacing: 0px;
            close_button := Button {
                width: 36px;
                tooltip_text: @tr("Close");
                click_sound: "";
                clicked => {
                    DockRootViewModelBindings.hide(docked_window_data.identifier);
                }
                Image {
                    width: 16px;
                    height: 16px;
                    horizontal_alignment: center;
                    vertical_alignment: center;
                    source: @image_url("../../images/app/close.png");
                }
            }
        }
    }
}
