import { Theme } from "./../../theme.slint";

import { DockedWindowView } from "../../views/docking/docked_window_view.slint";
import { OutputView } from "../../views/output/output_view.slint";
import { PropertyViewerView } from "../../views/property_viewer/property_viewer_view.slint";
import { ProcessSelectorView } from "../../views/process_selector/process_selector_view.slint";
import { ProjectExplorerView } from "../../views/project_explorer/project_explorer_view.slint";
import { ScanResultsView } from "../../views/scan_results/scan_results_view.slint";
import { SettingsView } from "../../views/settings/settings_view.slint";
import { DockRootViewModelBindings } from "./../../view_model_bindings.slint";

export component DockRoot inherits Rectangle {
    // TODO: These fail to fire until the window is done being dragged. It would be nice if we had real time.
    changed width => {
        DockRootViewModelBindings.update-dock-root-width(root.width);
    }
    changed height => {
        DockRootViewModelBindings.update-dock-root-height(root.height);
    }
    background: Theme.background-primary;
    init => {
        // These may no longer be needed.
        DockRootViewModelBindings.initial-dock-root-width = root.width;
        DockRootViewModelBindings.initial-dock-root-height = root.height;
    }

    // 'Settings' window
    settings-window := DockedWindowView {
        docked-window-data <=> DockRootViewModelBindings.settings-window;
        SettingsView { }
    }

    // 'ScanResults' window
    scan-results-window := DockedWindowView {
        docked-window-data <=> DockRootViewModelBindings.scan-results-window;
        ScanResultsView { }
    }

    // 'Output' window
    output-window := DockedWindowView {
        docked-window-data <=> DockRootViewModelBindings.output-window;
        OutputView { }
    }

    // 'ProcessSelector' window
    process-selector-window := DockedWindowView {
        docked-window-data <=> DockRootViewModelBindings.process-selector-window;
        ProcessSelectorView { }
    }

    // 'PropertyViewer' window
    property-viewer-window := DockedWindowView {
        docked-window-data <=> DockRootViewModelBindings.property-viewer-window;
        PropertyViewerView { }
    }

    // 'ProjectExplorer' window
    project-explorer-window := DockedWindowView {
        docked-window-data <=> DockRootViewModelBindings.project-explorer-window;
        ProjectExplorerView { }
    }
}
