import { Theme } from "./../../theme.slint";

import { DockRootViewModelBindings, DockedWindowViewData } from "./../../view_model_bindings.slint";

export component DockedWindowSplitters inherits Rectangle {
    in_out property <DockedWindowViewData> docked_window_data;
    in property <length> resize_padding;
    // Left border splitter
    Rectangle {
        x: 0;
        y: 0;
        width: root.resize_padding;
        height: root.docked_window_data.height;
        background: Theme.background_control;
        TouchArea {
            mouse_cursor: ew_resize;
            moved => {
                if (self.pressed && self.enabled) {
                    DockRootViewModelBindings.drag_left(
                        root.docked_window_data.identifier,
                        (self.mouse_x - self.pressed_x) / 1px,
                        (self.mouse_y - self.pressed_y) / 1px);
                }
            }
        }
    }

    // Right border splitter
    Rectangle {
        x: root.docked_window_data.width - root.resize_padding;
        y: 0;
        width: root.resize_padding;
        height: root.docked_window_data.height;
        background: Theme.background_control;
        TouchArea {
            mouse_cursor: ew_resize;
            moved => {
                if (self.pressed && self.enabled) {
                    DockRootViewModelBindings.drag_right(
                        root.docked_window_data.identifier,
                        (self.mouse_x - self.pressed_x) / 1px,
                        (self.mouse_y - self.pressed_y) / 1px);
                }
            }
        }
    }

    // Top border splitter
    Rectangle {
        x: 0;
        y: 0;
        width: root.docked_window_data.width;
        height: root.resize_padding;
        background: Theme.background_control;
        TouchArea {
            mouse_cursor: ns_resize;
            moved => {
                if (self.pressed && self.enabled) {
                    DockRootViewModelBindings.drag_top(
                        root.docked_window_data.identifier,
                        (self.mouse_x - self.pressed_x) / 1px,
                        (self.mouse_y - self.pressed_y) / 1px);
                }
            }
        }
    }

    // Bottom border splitter
    Rectangle {
        x: 0;
        y: root.docked_window_data.height - root.resize_padding;
        width: root.docked_window_data.width;
        height: root.resize_padding;
        background: Theme.background_control;
        TouchArea {
            mouse_cursor: ns_resize;
            moved => {
                if (self.pressed && self.enabled) {
                    DockRootViewModelBindings.drag_bottom(
                        root.docked_window_data.identifier,
                        (self.mouse_x - self.pressed_x) / 1px,
                        (self.mouse_y - self.pressed_y) / 1px);
                }
            }
        }
    }
}
