import { HorizontalBox, VerticalBox, Palette, ScrollView } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { OutputViewModelBindings } from "../../view_model_bindings.slint";

export component OutputView inherits Rectangle {
    content := ScrollView {
        padding: 0px;
        HorizontalLayout {
            padding: 4px;
            alignment: start;
            output-text-display := Text {
                text <=> OutputViewModelBindings.output-text;
                horizontal-alignment: left;
                vertical-alignment: top;
                color: Theme.foreground;
            }
        }
    }
}
