import { Theme } from "./../../theme.slint";
import { FocusTouchArea } from "./../focus_touch_area.slint";
import { StateLayer } from "./../state_layer.slint";

export component IconButton {
    in property <image> icon;
    in property <length> icon-width;
    in property <length> icon-height;
    callback clicked;

    forward-focus: touch-area;
    accessible-role: button;
    accessible-action-default => {
        touch-area.clicked();
    }

    touch-area := FocusTouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            root.clicked();
        }
    }

    state-layer := StateLayer {
        width: 100%;
        height: 100%;
        pressed: touch-area.is-pressed || touch-area.enter-pressed;
        has-focus: touch-area.has-focus;
        has-hover: touch-area.has-hover;
    }

    content-layer := HorizontalLayout {
        alignment: center;
        width: icon-width;
        height: icon-height;
        icon-image := Image {
            source: root.icon;
        }
    }
}
