import { Theme } from "./../../theme.slint";
import { FocusTouchArea } from "./../focus_touch_area.slint";
import { StateLayer } from "./../state_layer.slint";
import { Tooltip } from "../tooltips/tooltip.slint";

export component IconButton {
    in property <image> icon;
    in property <length> icon-width;
    in property <length> icon-height;
    in property <string> tooltip-text;
    callback clicked;

    forward-focus: touch-area;

    touch-area := FocusTouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            root.clicked();
        }
    }

    state-layer := StateLayer {
        width: 100%;
        height: 100%;
        pressed: touch-area.is-pressed || touch-area.enter-pressed;
        has-focus: touch-area.has-focus;
        has-hover: touch-area.has-hover;
    }

    content-layer := HorizontalLayout {
        alignment: center;
        width: icon-width;
        height: icon-height;
        icon-image := Image {
            source: root.icon;
        }
    }

    // TODO
    // if tooltip-text != "" {
       //  tooltip.show();
    // }

    tooltip := Tooltip {
        x: content-layer.x;
        y: content-layer.y + content-layer.height;
        text: root.tooltip-text;
    }
}
