import { FocusTouchArea } from "./../focus_touch_area.slint";
import { Theme } from "./../../theme.slint";

export component IconButton {
    in property <image> icon;
    callback clicked;

    forward-focus: touch-area;
    accessible-role: button;
    accessible-action-default => {
        touch-area.clicked();
    }

    touch-area := FocusTouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            root.clicked();
        }
    }

    content-layer := HorizontalLayout {
        alignment: center;
        icon-image := Image {
            source: root.icon;
        }
    }
}
