import { Theme } from "./../theme.slint";
import { TodoPalette, AnimationSettings } from "styling.slint";

export component StateLayer {
    in property <length> border-radius <=> state-layer.border-radius;
    in property <bool> pressed;
    in property <bool> has-hover;
    in property <bool> has-focus;
    in property <length> focus-padding: 2px;
    focus-border := Rectangle {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        width: root.width + 2 * root.focus-padding;
        height: root.height + 2 * root.focus-padding;
        border-radius: state-layer.border-radius + root.focus-padding;
        border-width: 2px;

        /*
        opacity: 1;
        states [
            focused when root.has-focus: {
                opacity: 1;
            }
        ]
        animate opacity { duration: AnimationSettings.color-duration; }
        */
    }

    state-layer := Rectangle {
        width: 100%;
        height: 100%;

        animate background { duration: AnimationSettings.color-duration; }
    }

    states [
        pressed when root.pressed: {
            state-layer.background: Theme.selected-background;
            focus-border.background: Theme.selected-border;
        }
        hoverd when root.has-hover: {
            state-layer.background: Theme.focused-background;
            focus-border.background: Theme.focused-border;
        }
    ]
}
