import { Theme } from "../../theme.slint";

import { FocusTouchArea } from "../focus_touch_area.slint";
import { StateLayer } from "../state_layer.slint";
import { Tooltip } from "../tooltips/tooltip.slint";

export component Checkbox inherits Rectangle {
    in_out property <bool> is_checked: false;
    in property <image> checked_icon: @image_url("../../images/app/close.png");
    in property <length> icon_width: 16px;
    in property <length> icon_height: 16px;
    in property <string> tooltip_text;
    callback check_changed(bool);
    width: 18px;
    height: 18px;
    background: Theme.background_control;
    border_width: 1px;
    border_color: Theme.submenu_border;
    forward_focus: touch_area;
    touch_area := FocusTouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            root.is_checked = !is_checked;
            root.check_changed(root.is_checked);
        }
    }

    state_layer := StateLayer {
        width: 100%;
        height: 100%;
        pressed: touch_area.is_pressed || touch_area.enter_pressed;
        has_focus: touch_area.has_focus;
        has_hover: touch_area.has_hover;
    }

    content_layer := HorizontalLayout {
        alignment: center;
        width: icon_width;
        height: icon_height;
        icon_image := Image {
            source: root.checked_icon;
            visible <=> root.is_checked;
        }
    }

    // JIRA
    // if tooltip_text != "" {
       //  tooltip.show();
    // }

    tooltip := Tooltip {
        x: content_layer.x;
        y: content_layer.y + content_layer.height;
        text: root.tooltip_text;
    }
}
