import { Theme } from "./../../theme.slint";

export component FakeCheckbox inherits Rectangle {
    in_out property <bool> is_checked: false;
    in property <image> checked_icon: @image_url("./../../images/app/close.png");
    in property <length> icon_width: 16px;
    in property <length> icon_height: 16px;
    in property <string> tooltip_text;
    width: 18px;
    height: 18px;
    background: Theme.background_control;
    border_width: 1px;
    border_color: Theme.submenu_border;
    content_layer := HorizontalLayout {
        alignment: center;
        width: icon_width;
        height: icon_height;
        icon_image := Image {
            source: root.checked_icon;
            visible <=> root.is_checked;
        }
    }
}
