import { HorizontalBox } from "std-widgets.slint";

import { Theme } from "./../../theme.slint";

import { Tooltip } from "../tooltips/tooltip.slint";
import { FakeCheckbox } from "fake_checkbox.slint";

export component TextFakeCheckbox {
    in_out property <bool> is_checked: false;
    in property <string> text;
    callback check_changed(bool);
    Rectangle {
        container := HorizontalBox {
            padding_top: root.padding_top;
            padding_bottom: root.padding_bottom;
            padding_left: root.padding_left;
            padding_right: root.padding_right;
            checkbox := FakeCheckbox {
                is_checked <=> root.is_checked;
            }

            text := Text {
                text: root.text;
                color: Theme.foreground;
            }
        }
    }
}
