import { HorizontalBox } from "std-widgets.slint";

import { Theme } from "./../../theme.slint";

import { Tooltip } from "../tooltips/tooltip.slint";
import { FakeCheckbox } from "fake_checkbox.slint";

export component TextFakeCheckbox {
    in-out property <bool> is-checked: false;
    in property <string> text;
    callback check-changed(bool);
    Rectangle {
        container := HorizontalBox {
            padding-top: root.padding-top;
            padding-bottom: root.padding-bottom;
            padding-left: root.padding-left;
            padding-right: root.padding-right;
            checkbox := FakeCheckbox {
                is-checked <=> root.is-checked;
            }

            text := Text {
                text: root.text;
                color: Theme.foreground;
            }
        }
    }
}
