import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "./../../theme.slint";
import { ContextMenu } from "../context_menu/context_menu.slint";

export component Tooltip inherits ContextMenu {
    in property <string> text;
    // in property <color> background: Theme.background_primary;
    in property <color> foreground: Theme.foreground;
    // in property <color> border_color: Theme.submenu_border;
    /*
    content := Text {
        text: root.text;
        wrap: word_wrap;
        color: root.foreground;
    }*/
}
