import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "./../../theme.slint";
import { ContextMenu } from "../context_menu/context_menu.slint";

export component Tooltip inherits ContextMenu {
    in property <string> text;
    // in property <color> background: Theme.background-primary;
    in property <color> foreground: Theme.foreground;
    // in property <color> border-color: Theme.submenu-border;
    content := Text {
        text: root.text;
        wrap: word-wrap;
        color: root.foreground;
    }
}
