import { Theme } from "../../../../olorin-gui/ui/theme.slint";

export component FooterView inherits Rectangle {
    height: 24px;
    Rectangle {
        border_bottom_left_radius: 8px;
        border_bottom_right_radius: 8px;
        background: Theme.background_primary;
    }

    HorizontalLayout {
        HorizontalLayout {
            alignment: start;
            padding: 0px;
            padding_left: 8px;
        }
    }
}
