import { ProgressIndicator, ScrollView } from "std-widgets.slint";

import { Theme } from "../../../../olorin-gui/ui/theme.slint";

import { BevelButton } from "../../../../olorin-gui/ui/components/buttons/bevel_button.slint";
import { FooterView } from "footer_view.slint";
import { TitleBarView } from "title_bar_view.slint";
import { InstallerViewModelBindings, WindowViewModelBindings } from "../view_model_bindings.slint";

export component InstallerWindowView inherits Window {
    title: @tr("Olorin Installer");
    // default_font_family: "Segoe UI";
    default_font_size: Theme.font_size_p;
    default_font_weight: Theme.font_weight;
    resize_border_width: 4px;
    width: 640px;
    height: 640px;
    background: transparent;
    no_frame: true;
    VerticalLayout {
        title_bar := TitleBarView {
            title: root.title;
        }

        Rectangle {
            background: Theme.background_primary;
            VerticalLayout {
                padding: 0px;
                spacing: 8px;
                Rectangle {
                    Text {
                        visible: !InstallerViewModelBindings.install_complete;
                        text: "Installing Olorin, please wait...";
                        color: Theme.foreground;
                    }

                    Text {
                        visible: InstallerViewModelBindings.install_complete;
                        text: "Olorin installed sucessfully!";
                        color: Theme.foreground;
                    }
                }

                Rectangle {
                    HorizontalLayout {
                        alignment: center;
                        ProgressIndicator {
                            width: 100%;
                            height: 32px;
                            progress: InstallerViewModelBindings.installer_progress;
                        }
                    }

                    VerticalLayout {
                        alignment: center;
                        HorizontalLayout {
                            alignment: center;
                            Text {
                                text: InstallerViewModelBindings.installer_progress_string;
                                color: Theme.foreground;
                            }
                        }
                    }
                }

                content := ScrollView {
                    width: root.width;
                    viewport_y: min(0px, 
                    - content.viewport_height + content.visible_height);
                    HorizontalLayout {
                        padding_top: 4px;
                        padding_bottom: 4px;
                        padding_left: 8px;
                        padding_right: 8px;
                        alignment: start;
                        output_text_display := Text {
                            text: InstallerViewModelBindings.installer_logs;
                            horizontal_alignment: left;
                            vertical_alignment: top;
                            wrap: word_wrap;
                            color: Theme.foreground;
                        }
                    }
                }

                HorizontalLayout {
                    alignment: center;
                    launch_button := BevelButton {
                        visible: InstallerViewModelBindings.install_complete;
                        background_color: Theme.background_control_primary;
                        bevel_color: Theme.background_control_primary_dark;
                        border_color: Theme.background_control_primary_dark;
                        border_width: 2px;
                        border_radius: 8px;
                        bevel_height: 4px;
                        width: 128px;
                        height: 40px;
                        clicked => {
                            InstallerViewModelBindings.launch_app();
                        }
                        Text {
                            text: @tr("Launch Olorin");
                            color: Theme.foreground;
                        }
                    }
                }
            }
        }

        footer := FooterView { }
    }
}
