import { ScrollView } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { OutputViewModelBindings } from "../../view_model_bindings.slint";

export component OutputView inherits Rectangle {
    content := ScrollView {
        padding: 0px;
        HorizontalLayout {
            padding: 4px;
            alignment: start;
            output_text_display := Text {
                text <=> OutputViewModelBindings.output_text;
                horizontal_alignment: left;
                vertical_alignment: top;
                color: Theme.foreground;
            }
        }
    }
}
