import { DataTypeView } from "../view_model_bindings.slint";

export component DataTypeIconConverter {
    public pure function data_type_string(data_type_view: DataTypeView) -> string {
        if (data_type_view == DataTypeView.i8) {
            return "i8";
        } else if (data_type_view == DataTypeView.u8) {
            return "u8";
        } else if (data_type_view == DataTypeView.i16) {
            return "i16";
        } else if (data_type_view == DataTypeView.i16be) {
            return "i16 (BE)";
        } else if (data_type_view == DataTypeView.u16) {
            return "u16";
        } else if (data_type_view == DataTypeView.u16be) {
            return "u16 (BE)";
        } else if (data_type_view == DataTypeView.i32) {
            return "i32";
        } else if (data_type_view == DataTypeView.i32be) {
            return "i32 (BE)";
        } else if (data_type_view == DataTypeView.u32) {
            return "u32";
        } else if (data_type_view == DataTypeView.u32be) {
            return "u32 (BE)";
        } else if (data_type_view == DataTypeView.u64) {
            return "u64";
        } else if (data_type_view == DataTypeView.u64be) {
            return "u64 (BE)";
        } else if (data_type_view == DataTypeView.i64) {
            return "i64";
        } else if (data_type_view == DataTypeView.i64be) {
            return "i64 (BE)";
        } else if (data_type_view == DataTypeView.f32) {
            return "f32";
        } else if (data_type_view == DataTypeView.f32be) {
            return "f32 (BE)";
        } else if (data_type_view == DataTypeView.f64) {
            return "f64";
        } else if (data_type_view == DataTypeView.f64be) {
            return "f64 (BE)";
        } else if (data_type_view == DataTypeView.string) {
            return "string";
        } else if (data_type_view == DataTypeView.bytes) {
            return "u8 [ ]";
        } else if (data_type_view == DataTypeView.string) {
            return "String";
        }
        return @tr("Data Type");
    }
    public pure function data_type_source(data_type_view: DataTypeView) -> image {
        if (data_type_view == DataTypeView.i8) {
            return @image-url("./../images/data_types/blue_blocks_1.png");
        } else if (data_type_view == DataTypeView.u8) {
            return @image-url("./../images/data_types/purple_blocks_1.png");
        } else if (data_type_view == DataTypeView.i16) {
            return @image-url("./../images/data_types/blue_blocks_2.png");
        } else if (data_type_view == DataTypeView.i16be) {
            return @image-url("./../images/data_types/blue_blocks_2.png");
        } else if (data_type_view == DataTypeView.u16) {
            return @image-url("./../images/data_types/purple_blocks_2.png");
        } else if (data_type_view == DataTypeView.u16be) {
            return @image-url("./../images/data_types/purple_blocks_2.png");
        } else if (data_type_view == DataTypeView.i32) {
            return @image-url("./../images/data_types/blue_blocks_4.png");
        } else if (data_type_view == DataTypeView.i32be) {
            return @image-url("./../images/data_types/blue_blocks_4.png");
        } else if (data_type_view == DataTypeView.u32) {
            return @image-url("./../images/data_types/purple_blocks_4.png");
        } else if (data_type_view == DataTypeView.u32be) {
            return @image-url("./../images/data_types/purple_blocks_4.png");
        } else if (data_type_view == DataTypeView.i64) {
            return @image-url("./../images/data_types/blue_blocks_8.png");
        } else if (data_type_view == DataTypeView.i64be) {
            return @image-url("./../images/data_types/blue_blocks_8.png");
        } else if (data_type_view == DataTypeView.u64) {
            return @image-url("./../images/data_types/purple_blocks_8.png");
        } else if (data_type_view == DataTypeView.u64be) {
            return @image-url("./../images/data_types/purple_blocks_8.png");
        } else if (data_type_view == DataTypeView.f32) {
            return @image-url("./../images/data_types/orange_blocks_4.png");
        } else if (data_type_view == DataTypeView.f32be) {
            return @image-url("./../images/data_types/orange_blocks_4.png");
        } else if (data_type_view == DataTypeView.f64) {
            return @image-url("./../images/data_types/orange_blocks_8.png");
        } else if (data_type_view == DataTypeView.f64be) {
            return @image-url("./../images/data_types/orange_blocks_8.png");
        } else if (data_type_view == DataTypeView.bytes) {
            return @image-url("./../images/data_types/blue_blocks_array.png");
        } else if (data_type_view == DataTypeView.string) {
            return @image-url("./../images/projects/static_type.png");
        }
        return @image-url("./../images/data_types/blue_blocks_4.png");
    }
}
