import { DisplayValueTypeView } from "../view_model_bindings.slint";

export component DisplayValueTypeConverter {
    public pure function display_value_type_to_string(display_value_type: DisplayValueTypeView) -> string {
        if display_value_type == DisplayValueTypeView.bool {
            return "bool";
        } else if display_value_type == DisplayValueTypeView.string {
            return "string";
        } else if display_value_type == DisplayValueTypeView.binary {
            return "binary";
        } else if display_value_type == DisplayValueTypeView.decimal {
            return "decimal";
        } else if display_value_type == DisplayValueTypeView.hexadecimal {
            return "hexadecimal";
        } else if display_value_type == DisplayValueTypeView.address {
            return "address";
        } else if display_value_type == DisplayValueTypeView.byte_array {
            return "byte array";
        } else if display_value_type == DisplayValueTypeView.data_type_ref {
            return "data type";
        } else if display_value_type == DisplayValueTypeView.enumeration {
            return "enumeration";
        }
        return "unknown";
    }
}
