import { MemoryAlignmentView } from "../view_model_bindings.slint";

export component MemoryAlignmentIconConverter {
    public pure function memory_alignment_source(memory_alignment_view: MemoryAlignmentView) -> image {
        if (memory_alignment_view == MemoryAlignmentView.alignment_1) {
            return @image-url("./../images/data_types/purple_blocks_1.png");
        } else if (memory_alignment_view == MemoryAlignmentView.alignment_2) {
            return @image-url("./../images/data_types/purple_blocks_2.png");
        } else if (memory_alignment_view == MemoryAlignmentView.alignment_4) {
            return @image-url("./../images/data_types/purple_blocks_4.png");
        } else if (memory_alignment_view == MemoryAlignmentView.alignment_8) {
            return @image-url("./../images/data_types/purple_blocks_8.png");
        }
        return @image-url("./../images/unknown.png");
    }
}
