import { IconView, MemoryReadModeView } from "../view_model_bindings.slint";

export component MemoryReadModeIconConverter {
    public pure function memory_read_mode_source(memory_read_mode_view: MemoryReadModeView) -> IconView {
        if (memory_read_mode_view == MemoryReadModeView.skip) {
            return IconView.skip;
        } else if (memory_read_mode_view == MemoryReadModeView.read_interleaved_with_scan) {
            return IconView.read_interleaved_with_scan;
        } else if (memory_read_mode_view == MemoryReadModeView.read_before_scan) {
            return IconView.read_before_scan;
        }
        return IconView.unknown;
    }
}
