import { IconView, MemoryAlignmentView } from "../view_model_bindings.slint";

export component MemoryAlignmentIconConverter {
    public pure function memory_alignment_source(memory_alignment_view: MemoryAlignmentView) -> IconView {
        if (memory_alignment_view == MemoryAlignmentView.alignment_1) {
            return IconView.alignment_1;
        } else if (memory_alignment_view == MemoryAlignmentView.alignment_2) {
            return IconView.alignment_2;
        } else if (memory_alignment_view == MemoryAlignmentView.alignment_4) {
            return IconView.alignment_4;
        } else if (memory_alignment_view == MemoryAlignmentView.alignment_8) {
            return IconView.alignment_8;
        }
        return IconView.unknown;
    }
}
