import { IconView, FloatingPointToleranceView } from "../view_model_bindings.slint";

export component FloatingPointToleranceIconConverter {
    public pure function floating_point_tolerance_to_icon_view(floating_point_tolerance_view: FloatingPointToleranceView) -> IconView {
        if (floating_point_tolerance_view == FloatingPointToleranceView.tolerance_10e1) {
            return IconView.tolerance_10e1;
        } else if (floating_point_tolerance_view == FloatingPointToleranceView.tolerance_10e2) {
            return IconView.tolerance_10e2;
        } else if (floating_point_tolerance_view == FloatingPointToleranceView.tolerance_10e3) {
            return IconView.tolerance_10e3;
        } else if (floating_point_tolerance_view == FloatingPointToleranceView.tolerance_10e4) {
            return IconView.tolerance_10e4;
        } else if (floating_point_tolerance_view == FloatingPointToleranceView.tolerance_10e5) {
            return IconView.tolerance_10e5;
        } else if (floating_point_tolerance_view == FloatingPointToleranceView.tolerance_epsilon) {
            return IconView.tolerance_epsilon;
        }
        return IconView.unknown;
    }
}
