import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";
import { BevelButton } from "../../components/buttons/bevel_button.slint";

export component ProjectSelectorTab inherits Rectangle {
    content := VerticalBox {
        padding: 0px;
        spacing: 0px;
        @children
    }

    BevelButton {
        width: 128px;
        height: 48px;
        bevel_height: 4px;
        Text {
            color: Theme.foreground;
            text: @tr("New Project");
        }
    }
}
