import { Theme } from "../../theme.slint";

import { ProjectExplorerViewModelBindings } from "../../view_model_bindings.slint";
import { ProjectOutlineTab } from "project_outline/project_outline_tab.slint";
import { ProjectSelectorTab } from "project_selector/project_selector_tab.slint";

export component ProjectExplorerView inherits Rectangle {
    if ProjectExplorerViewModelBindings.is_project_open: project_outline_tab := ProjectOutlineTab { }
    if !ProjectExplorerViewModelBindings.is_project_open: project_selector_tab := ProjectSelectorTab { }
}
