export global Theme {
    in-out property <brush> border-blue: #007ACC;
    in-out property <brush> background-primary: #333333;
    in-out property <brush> background-secondary: #272727;
    in-out property <brush> foreground: #ffffff;
    in-out property <brush> submenu-border: #cdcdcd;
    in-out property <brush> selected-background: #26A0DA3D;
    in-out property <brush> selected-border: #26A0DAFF;
    in-out property <brush> focused-background: #15506CFF;
    in-out property <brush> focused-border: #26A0DAFF;
}

export global AnimationSettings {
    out property <duration> color-duration: 50ms;
    out property <duration> move-duration: 50ms;
    out property <easing> move-easing: cubic-bezier(0.3, 0.0, 0.8, 0.15);
}
