export global Theme {
    in-out property <brush> border-blue: #007ACC;
    in-out property <brush> background-primary: #333333;
    in-out property <brush> background-panel: #272727;
    in-out property <brush> background-control: #444444;
    in-out property <brush> foreground: #ffffff;
    in-out property <brush> foreground-preview: #afafaf;
    in-out property <brush> submenu-border: #7f7f7f;
    in-out property <brush> selected-background: #26A0DA3D;
    in-out property <brush> selected-border: #26A0DAFF;
    in-out property <brush> focused-background: #15506CFF;
    in-out property <brush> focused-border: #26A0DAFF;
    
    // Font
    in-out property <int> font-weight: 525;
    in-out property <length> font-size-window-title: 11pt;
    in-out property <length> font-size-s: 9pt;
    in-out property <length> font-size-p: 11pt;
    in-out property <length> font-size-h1: 32pt;
    in-out property <length> font-size-h2: 24pt;
    in-out property <length> font-size-h3: 20pt;
    in-out property <length> font-size-h4: 17pt;
    in-out property <length> font-size-h5: 15pt;
}

export global AnimationSettings {
    out property <duration> color-duration: 50ms;
    out property <duration> move-duration: 50ms;
    out property <easing> move-easing: cubic-bezier(0.3, 0.0, 0.8, 0.15);
}
