/// This file contains every binding between the UI (view) and Rust (view-model).
/// The MVVM pattern is really simple. You have:
/// - A view (.slint files)
/// - A model (squalr libraries)
/// - And a view-model (glue that connects the two)
/// The bindings below are how the view <=> view-model connect to one another.

export global WindowViewModelBindings {
    callback close();
    callback maximize();
    callback minimize();
    callback double-clicked();
    callback drag(int, int);
    callback play-sound(string);
}

export struct DockedWindowViewData {
    identifier: string,
    is-docked: bool,
    is-visible: bool,
    is-dragging: bool,
    position-x: length,
    position-y: length,
    width: length,
    height: length,
    tab-ids: [string],
    active-tab-id: string,
}

export enum RedockTarget { left, right, up, down, center }

export global DockRootViewModelBindings {
    in-out property <length> initial-dock-root-width;
    in-out property <length> initial-dock-root-height;
    in-out property <string> active-dragged-window-id;
    in-out property <bool> is-dragging-window;
    pure callback update-dock-root-width(width: length);
    pure callback update-dock-root-height(height: length);
    pure callback update-dock-root-size(width: length, height: length) -> length;
    pure callback update-active-tab-id(identifier: string);
    pure callback get-tab-text(identifier: string) -> string;
    callback try-redock-window(identifier: string, target-identifier: string, redock-target: RedockTarget);
    callback reset-layout();
    callback hide(identifier: string);
    callback drag-left(identifier: string, delta-x: int, delta-y: int);
    callback drag-right(identifier: string, delta-x: int, delta-y: int);
    callback drag-top(identifier: string, delta-x: int, delta-y: int);
    callback drag-bottom(identifier: string, delta-x: int, delta-y: int);
    in-out property <DockedWindowViewData> scan-results-window;
    in-out property <DockedWindowViewData> output-window;
    in-out property <DockedWindowViewData> process-selector-window;
    in-out property <DockedWindowViewData> property-viewer-window;
    in-out property <DockedWindowViewData> project-explorer-window;
    in-out property <DockedWindowViewData> settings-window;
}

export struct ProcessViewData {
    process-id-str: string,
    process-id: int,
    name: string,
    icon: image,
}

export global ProcessSelectorViewModelBindings {
    callback refresh-windowed-process-list();
    callback refresh-full-process-list();
    callback select-process(ProcessViewData);
    in property <[ProcessViewData]> windowed-processes;
    in property <[ProcessViewData]> processes;
    in property <ProcessViewData> selected-process;
}

export global OutputViewModelBindings {
    in-out property <string> output-text;
}

export global ScanViewModelBindings {
    callback new_scan();
    callback set_scan_constraint(int);
}

export global MemorySettingsViewModelBindings {
    in-out property <bool> memory_type_none;
    callback memory_type_none_changed(bool);
    in-out property <bool> memory_type_private;
    callback memory_type_private_changed(bool);
    in-out property <bool> memory_type_image;
    callback memory_type_image_changed(bool);
    in-out property <bool> memory_type_mapped;
    callback memory_type_mapped_changed(bool);
    in-out property <bool> required_write;
    callback required_write_changed(bool);
    in-out property <bool> required_execute;
    callback required_execute_changed(bool);
    in-out property <bool> required_copy_on_write;
    callback required_copy_on_write_changed(bool);
    in-out property <bool> excluded_write;
    callback excluded_write_changed(bool);
    in-out property <bool> excluded_execute;
    callback excluded_execute_changed(bool);
    in-out property <bool> excluded_copy_on_write;
    callback excluded_copy_on_write_changed(bool);
    in-out property <string> start_address;
    callback start_address_changed(string);
    in-out property <string> end_address;
    callback end_address_changed(string);
    in-out property <bool> only_query_usermode;
    callback only_query_usermode_changed(bool);
}

export global ScanSettingsViewModelBindings {
    in-out property <int> results_page_size;
    callback results_page_size_changed(int);
    in-out property <int> results_read_interval;
    callback results_read_interval_changed(int);
    in-out property <int> table_read_interval;
    callback table_read_interval_changed(int);
    in-out property <int> freeze_interval;
    callback freeze_interval_changed(int);
    // Option<MemoryAlignment>,
    in-out property <int> memory_alignment;
    callback memory_alignment_changed(int);
    // FloatingPointTolerance,
    in-out property <int> floating_point_tolerance;
    callback floating_point_tolerance_changed(int);
}

export global ProjectExplorerViewModelBindings { }

export global ScanResultsViewModelBindings { }

export global PointerScanResultsViewModelBindings { }

export global PropertyViewerViewModelBindings { }
