export global InstallerViewModelBindings {
    in_out property <float> installer_progress: 0.0;
    in_out property <string> installer_progress_string: 0.0;
    in_out property <string> installer_logs;
    in_out property <bool> install_complete: false;
    callback launch_app();
}

export global EngineViewModelBindings {
    callback play_sound(string);
    callback open_url(string);
    in_out property <string> app_version;
    in_out property <angle> loading_spinner_rotation;
}

export global WindowViewModelBindings {
    callback close();
    callback maximize();
    callback minimize();
    callback double_clicked();
    callback drag(int, int);
}
