import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "./../../theme.slint";

import { ToolbarMenuItem, ToolbarMenuItemData } from "./toolbar_menu_item.slint";

export struct ToolbarMenuData {
    header: string,
    items: [ToolbarMenuItemData],
}

export component ToolbarMenu inherits Rectangle {
    in-out property <[ToolbarMenuData]> menus;
    in property <length> bottom-padding: 4px;
    callback onItemClicked(string);
    height: 24px + root.bottom-padding;
    background: Theme.background-primary;
    HorizontalLayout {
        content := HorizontalBox {
            alignment: start;
            padding-left: 0px;
            padding-right: 0px;
            padding-top: 0px;
            padding-bottom: bottom-padding;
            spacing: 0px;
            for menu in menus: ToolbarMenuItem {
                parent-toolbar-size: content.width;
                text: menu.header;
                items: menu.items;
                onItemClicked(key) => {
                    root.onItemClicked(key);
                }
            }
        }

        fill := Rectangle {
            horizontal-stretch: 100%;
        }
    }
}
