import { Theme } from "./../../theme.slint";
import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";
import { ToolbarMenuItem, ToolbarMenuItemData } from "./toolbar_menu_item.slint";

export struct ToolbarMenuData {
    header: string,
    items: [ToolbarMenuItemData],
}

export component ToolbarMenu inherits Rectangle {
    in-out property <[ToolbarMenuData]> menus;
    height: 24px;
    background: Theme.background-primary;
    HorizontalLayout {
        content := HorizontalBox {
            alignment: start;
            padding: 0px;
            spacing: 0px;
            for menu in menus: ToolbarMenuItem {
                parent-toolbar-size: content.width;
                text: menu.header;
                items: menu.items;
            }
        }

        fill := Rectangle {
            horizontal-stretch: 100%;
        }
    }
}
