import { Theme } from "../../../../theme.slint";

import { ConversionsViewModelBindings, ScanSettingsViewModelBindings, MemoryReadModeView } from "../../../../view_model_bindings.slint";
import { MemoryReadModeIconConverter } from "../../../../converters/memory_read_mode_icon_converter.slint";
import { IconConverter } from "../../../../converters/icon_converter.slint";
import { Button } from "../../../../components/buttons/button.slint";
import { ContextMenu } from "../../../../components/context_menu/context_menu.slint";

export component SettingChooserMemoryReadModeEntry inherits Button {
    in property <MemoryReadModeView> memory_read_mode;
    callback onClicked;
    memory_read_mode_icon_converter := MemoryReadModeIconConverter { }

    icon_converter := IconConverter { }

    height: 24px;
    clicked => {
        ScanSettingsViewModelBindings.memory_read_mode = root.memory_read_mode;
        ScanSettingsViewModelBindings.memory_read_mode_changed(root.memory_read_mode);
        root.onClicked();
    }
    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            padding_left: 4px;
            padding_right: 8px;
            spacing: 8px;
            alignment: start;
            Image {
                width: 16px;
                height: 16px;
                horizontal_alignment: center;
                vertical_alignment: center;
                source: icon_converter.icon_view_to_image(memory_read_mode_icon_converter.memory_read_mode_source(root.memory_read_mode));
            }

            Text {
                color: Theme.foreground;
                horizontal_alignment: left;
                vertical_alignment: center;
                text: ConversionsViewModelBindings.get_memory_read_mode_string(root.memory_read_mode);
            }
        }
    }
}
