import { ScrollView } from "std-widgets.slint";

import { Theme } from "../../../theme.slint";

import { ProjectExplorerViewModelBindings } from "../../../view_model_bindings.slint";
import { Button } from "../../../components/buttons/button.slint";
import { BevelButton } from "../../../components/buttons/bevel_button.slint";
import { ProjectItemEntry } from "project_item_entry.slint";
import { ProjectOutlineHeader } from "project_outline_header.slint";

export component ProjectOutlineTab inherits Rectangle {
    property <float> display_splitter_ratio: 0.5;
    VerticalLayout {
        padding: 0px;
        spacing: 0px;
        ProjectOutlineHeader { }

        ScrollView {
            content := VerticalLayout {
                padding: 0px;
                spacing: 0px;
                for index in ProjectExplorerViewModelBindings.project_items.length: ProjectItemEntry {
                    project_view_data: ProjectExplorerViewModelBindings.project_items[index];
                    display_value_splitter_location: content.width * root.display_splitter_ratio;
                }
            }
        }
    }
}
