import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../../theme.slint";

import { ProjectExplorerViewModelBindings } from "../../../view_model_bindings.slint";
import { BevelButton } from "../../../components/buttons/bevel_button.slint";

export component ProjectOutlineTab inherits Rectangle {
    content := VerticalBox {
        padding: 0px;
        spacing: 0px;
        @children
    }
}
