import { Theme } from "../../../../theme.slint";

import { ConversionsViewModelBindings, ScanSettingsViewModelBindings, MemoryAlignmentView } from "../../../../view_model_bindings.slint";
import { MemoryAlignmentIconConverter } from "../../../../converters/memory_alignment_icon_converter.slint";
import { IconConverter } from "../../../../converters/icon_converter.slint";
import { Button } from "../../../../components/buttons/button.slint";

export component SettingChooserMemoryAlignmentEntry inherits Button {
    in property <MemoryAlignmentView> memory_alignment;
    callback onClicked;
    memory_alignment_icon_converter := MemoryAlignmentIconConverter { }

    icon_converter := IconConverter { }

    height: 24px;
    clicked => {
        ScanSettingsViewModelBindings.memory_alignment = root.memory_alignment;
        ScanSettingsViewModelBindings.memory_alignment_changed(root.memory_alignment);
        root.onClicked();
    }
    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            padding_left: 4px;
            padding_right: 8px;
            spacing: 8px;
            alignment: start;
            padding: 0px;
            Image {
                width: 16px;
                height: 16px;
                horizontal_alignment: center;
                vertical_alignment: center;
                source: icon_converter.icon_view_to_image( memory_alignment_icon_converter.memory_alignment_source(root.memory_alignment));
            }

            Text {
                color: Theme.foreground;
                horizontal_alignment: left;
                vertical_alignment: center;
                text: ConversionsViewModelBindings.get_memory_alignment_string(root.memory_alignment);
            }
        }
    }
}
