export global Theme {
    in_out property <brush> border_blue: #007ACC;
    in_out property <brush> background_primary: #333333;
    in_out property <brush> background_panel: #272727;
    in_out property <brush> background_control: #444444;
    in_out property <brush> foreground: #ffffff;
    in_out property <brush> foreground_preview: #afafaf;
    in_out property <brush> submenu_border: #7f7f7f;
    in_out property <brush> selected_background: #26A0DA3D;
    in_out property <brush> selected_border: #26A0DAFF;
    in_out property <brush> transparent: #00000000;
    
    // Background colors primarily used for controls (ie buttons).
    in_out property <brush> background_control_primary: #1e5492;
    in_out property <brush> background_control_primary_dark: #061e3e;
    in_out property <brush> background_control_secondary: #434e51;
    in_out property <brush> background_control_secondary_dark: #1f2526;
    in_out property <brush> background_control_success: #14a44d;
    in_out property <brush> background_control_success_dark: #0e7236;
    in_out property <brush> background_control_danger: #dc4c64;
    in_out property <brush> background_control_danger_dark: #ae3c4f;
    in_out property <brush> background_control_warning: #e4a11b;
    in_out property <brush> background_control_warning_dark: #b07d15;
    in_out property <brush> background_control_info: #32c4e6;
    in_out property <brush> background_control_info_dark: #0b2d5d;
    in_out property <brush> background_control_light: #fbfbfb;
    in_out property <brush> background_control_border: #201c1c;

    // Special Theme
    in_out property <brush> dec_white: #ffffff;
    in_out property <brush> dec_white_preview: #afafaf;
    in_out property <brush> bin_blue: #0291f0;
    in_out property <brush> bin_blue_preview: #66a2c9;
    in_out property <brush> hex_green: #14a44d;
    in_out property <brush> hex_green_preview: #75a075;
    in_out property <brush> error_red: #e72020;
    
    // Font
    in_out property <string> default_font_family: "Segoe UI";
    in_out property <string> mono_font_family: "Consolas";
    in_out property <int> font_weight: 525;
    in_out property <length> font_size_window_title: 11pt;
    in_out property <length> font_size_small: 9pt;
    in_out property <length> font_size_normal: 11pt;
    in_out property <length> font_size_h1: 32pt;
    in_out property <length> font_size_h2: 24pt;
    in_out property <length> font_size_h3: 20pt;
    in_out property <length> font_size_h4: 17pt;
    in_out property <length> font_size_header: 14pt;
    
    // Focus
    in_out property <brush> focused_background: #15506CFF;
    in_out property <brush> focused_border: #26A0DAFF;
    in_out property <brush> hover_tint: #FFFFFF10;
    in_out property <brush> pressed_tint: #00000020;
}

export global AnimationSettings {
    out property <duration> color_duration: 50ms;
    out property <duration> move_duration: 50ms;
    out property <easing> move_easing: cubic_bezier(0.3, 0.0, 0.8, 0.15);
}
