import { CheckBox, StandardListView } from "std-widgets.slint";
import { AboutPage, ControlsPage, EasingsPage, ListViewPage, TableViewPage, TableViewPageAdapter, TextEditPage } from "pages/pages.slint";
import { GallerySettings } from "gallery_settings.slint";
import { TitleBar } from "title_bar.slint";
import { SideBar } from "side_bar.slint";

export { TableViewPageAdapter }

export component MainWindow inherits Window {
    preferred-width: 1280px;
    preferred-height: 640px;
    no-frame: true;
    title: @tr("Squalr");
    // icon: @image-url("../../logo/slint-logo-small-light.png");
    VerticalLayout {
        title-bar := TitleBar {
            title: @tr("Squalr");
        }

        HorizontalLayout {
            side-bar := SideBar {
                title: @tr("Slint Widgets Gallery");
                model: [
                    @tr("Menu" => "Controls"),
                    @tr("Menu" => "ListView"),
                    @tr("Menu" => "TableView"),
                    @tr("Menu" => "TextEdit"),
                    @tr("Menu" => "Easings"),
                    @tr("Menu" => "About")
                ];
            }

            if(side-bar.current-item == 0): ControlsPage { }
            if(side-bar.current-item == 1): ListViewPage { }
            if(side-bar.current-item == 2): TableViewPage { }
            if(side-bar.current-item == 3): TextEditPage { }
            if(side-bar.current-item == 4): EasingsPage { }
            if(side-bar.current-item == 5): AboutPage { }
        }
    }
}
