import { Theme } from "../../theme.slint";

import { ProcessSelectorViewModelBindings, ProcessViewData } from "../../view_model_bindings.slint";
import { ContextMenu } from "../../components/context_menu/context_menu.slint";
import { Button } from "../../components/buttons/button.slint";

export component ProcessEntry inherits Button {
    in property <ProcessViewData> process_view_data;
    callback on_click();
    clicked => {
        ProcessSelectorViewModelBindings.select_process(root.process_view_data);
        root.on_click();
    }
    HorizontalLayout {
        spacing: 8px;
        padding: 8px;
        Image {
            width: 16px;
            height: 16px;
            horizontal_alignment: center;
            vertical_alignment: center;
            source: process_view_data.icon;
        }

        Text {
            color: Theme.foreground;
            horizontal_alignment: left;
            vertical_alignment: center;
            text: process_view_data.name;
        }
    }
}
