import { ScrollView } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { ProcessSelectorViewModelBindings, ProcessViewData } from "../../view_model_bindings.slint";
import { ProcessEntry } from "process_entry.slint";
import { ContextMenu } from "../../components/context_menu/context_menu.slint";
import { Button } from "../../components/buttons/button.slint";

export component ProcessQuickSelector inherits Rectangle {
    background: Theme.background_control;
    border_color: Theme.submenu_border;
    border_width: 1px;
    min_width: 192px;
    dropdown_button := Button {
        width: 100%;
        height: 24px;
        clicked => {
            ProcessSelectorViewModelBindings.refresh_windowed_process_list();
            context_menu.show();
        }
        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                padding_left: 4px;
                padding-right: 32px;
                alignment: start;
                Image {
                    width: 16px;
                    height: 16px;
                    horizontal_alignment: center;
                    vertical_alignment: center;
                    source: ProcessSelectorViewModelBindings.selected_process.icon;
                }

                Text {
                    color: Theme.foreground;
                    horizontal_alignment: left;
                    vertical_alignment: center;
                    text: ProcessSelectorViewModelBindings.selected_process.name;
                }
            }
        }

        HorizontalLayout {
            alignment: end;
            padding_right: 4px;
            Image {
                source: @image_url("../../images/navigation/down_arrow_small.png");
            }
        }

        HorizontalLayout {
            alignment: end;
            padding_right: 24px;
            Rectangle {
                background: Theme.submenu_border;
                width: 1px;
            }
        }
    }

    context_menu := ContextMenu {
        close_policy: close_on_click_outside;
        x: dropdown_button.x;
        y: dropdown_button.y + dropdown_button.height;
        min_height: 512px;
        Rectangle {
            background: Theme.background_control;
            border_color: Theme.submenu_border;
            border_width: 1px;
            width: 312px;
            ScrollView {
                padding: 0px;
                VerticalLayout {
                    padding: 0px;
                    spacing: 0px;
                    for process_entry in ProcessSelectorViewModelBindings.windowed_processes: ProcessEntry {
                        process_view_data: process_entry;
                        on_click => {
                            context_menu.close();
                        }
                    }
                }
            }
        }
    }
}
