import { HorizontalBox, VerticalBox, Palette, ScrollView } from "std-widgets.slint";

import { Theme } from "../../theme.slint";
import { ProcessSelectorViewModelBindings, ProcessViewData } from "../../view_model_bindings.slint";

import { ProcessEntry } from "process_entry.slint";
import { ContextMenu } from "../../components/context_menu/context_menu.slint";
import { Button } from "../../components/buttons/button.slint";

export component ProcessQuickSelector inherits Rectangle {
    background: Theme.background-control;
    border-color: Theme.submenu-border;
    border-width: 1px;
    width: 192px;
    dropdown-button := Button {
        width: 100%;
        height: 24px;
        clicked => {
            ProcessSelectorViewModelBindings.refresh-windowed-process-list();
            context-menu.show();
        }
        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                padding-left: 4px;
                alignment: start;
                HorizontalBox {
                    padding: 0px;
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        source: ProcessSelectorViewModelBindings.selected-process.icon;
                    }

                    Text {
                        color: Theme.foreground;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        text: ProcessSelectorViewModelBindings.selected-process.name;
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: end;
            padding-right: 4px;
            Image {
                source: @image-url("../../images/navigation/down_arrow_small.png");
            }
        }

        HorizontalLayout {
            alignment: end;
            padding-right: 24px;
            Rectangle {
                background: Theme.submenu-border;
                width: 1px;
            }
        }
    }

    context-menu := ContextMenu {
        close-policy: close-on-click-outside;
        x: dropdown-button.x;
        y: dropdown-button.y + dropdown-button.height;
        min-height: 512px;
        Rectangle {
            background: Theme.background-control;
            border-color: Theme.submenu-border;
            border-width: 1px;
            width: 312px;
            ScrollView {
                padding: 0px;
                VerticalBox {
                    padding: 0px;
                    spacing: 0px;
                    for process-entry in ProcessSelectorViewModelBindings.windowed-processes: ProcessEntry {
                        process_view_data: process-entry;
                        on-click => {
                            context-menu.close();
                        }
                    }
                }
            }
        }
    }
}
