import { Theme, AnimationSettings } from "./../theme.slint";

export component StateLayer {
    in property <bool> pressed;
    in property <bool> has-hover;
    in property <bool> has-focus;

    state-layer := Rectangle {
        border-radius: 1px;
        border-width: 1px;

        animate border-color { duration: AnimationSettings.color-duration; }
        animate background { duration: AnimationSettings.color-duration; }
    }

    states [
        pressed when root.pressed: {
            state-layer.background: Theme.selected-background;
            state-layer.border-color: Theme.selected-border;
        }
        hovered when root.has-hover: {
            state-layer.background: Theme.focused-background;
            state-layer.border-color: Theme.focused-border;
        }
    ]
}
