import {Theme} from "./../../theme.slint";
import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

export component ContextMenuItem inherits Rectangle {
    in property <bool> selected;
    in property <bool> has-focus;
    in-out property <string> text <=> label.text;
    callback clicked <=> touch.clicked;
    label := Text {
        color: Theme.foreground;
        vertical-alignment: center;
        horizontal-alignment: left;
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}
