import {Theme} from "./../../theme.slint";
import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

export component ContextMenu inherits PopupWindow {
    Rectangle {
        height: 100%;
        width: 100%;
        background: Theme.background-primary;
        VerticalLayout {
            bottom := VerticalBox {
                padding-left: 8px;
                padding-right: 8px;
                padding-top: 4px;
                padding-bottom: 4px;
                spacing: 8px;
                @children
            }
        }
    }
}
