import { Theme } from "./../theme.slint";
import { HorizontalBox, VerticalBox, Palette, GridBox } from "std-widgets.slint";
import { ContextMenu } from "./../components/context_menu/context_menu.slint";
import { IconTextButton } from "../components/buttons/icon_text_button.slint";

export component DataTypeSelector inherits Rectangle {
    background: Theme.background-control;
    border-color: Theme.submenu-border;
    border-width: 1px;
    width: 96px;
    text-button := IconTextButton {
        width: 100%;
        height: 100%;
        icon: @image-url("./../images/data_types/blue_blocks_4.png");
        icon-width: 24px;
        icon-height: 24px;
        text: "Data Type";
        text-padding-top: 0px;
        text-padding-bottom: 0px;
        text-horizontal-alignment: left;
        text-vertical-alignment: center;
        clicked => {
            context-menu.show();
        }
    }

    context-menu := ContextMenu {
        x: text-button.x;
        y: text-button.y + text-button.height;
        width: 192px;
        content := GridLayout {
            padding: 0px;
            spacing: 0px;
            Row {
                data-type-u8 := IconTextButton {
                    icon: @image-url("./../images/data_types/purple_blocks_1.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "u8";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: u8. Size: 1 byte. Also known as an unsigned byte, or byte.";
                    clicked => {
                    }
                }

                data-type-i8 := IconTextButton {
                    icon: @image-url("./../images/data_types/blue_blocks_1.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "i8";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: i8. Size: 1 byte. Also known as a signed byte, or sbyte.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-i16 := IconTextButton {
                    icon: @image-url("./../images/data_types/blue_blocks_2.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "i16";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: i16. Size: 2 bytes. Also known as a (signed) short integer, or short.";
                    clicked => {
                    }
                }

                data-type-i16be := IconTextButton {
                    icon: @image-url("./../images/data_types/blue_blocks_2.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "i16 (BE)";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: i16 (Big Endian). Size: 2 bytes. Also known as a (signed) short integer, or short. Big Endian is generally only used in certain console emulators.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-i32 := IconTextButton {
                    icon: @image-url("./../images/data_types/blue_blocks_4.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "i32";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: i32. Size: 4 bytes. Also known as a (signed) integer, or int.";
                    clicked => {
                    }
                }

                data-type-i32be := IconTextButton {
                    icon: @image-url("./../images/data_types/blue_blocks_4.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "i32 (BE)";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: i32 (Big Endian). Size: 4 bytes. Also known as a (signed) integer, or int. Big Endian is generally only used in certain console emulators.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-i64 := IconTextButton {
                    icon: @image-url("./../images/data_types/blue_blocks_8.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "i64";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: i64. Size: 8 bytes. Also known as a (signed) long integer, long long, or long.";
                    clicked => {
                    }
                }

                data-type-i64be := IconTextButton {
                    icon: @image-url("./../images/data_types/blue_blocks_8.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "i64 (BE)";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: i64 (Big Endian). Size: 8 bytes. Also known as a (signed) long integer, long long, or long. Big Endian is generally only used in certain console emulators.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-u16 := IconTextButton {
                    icon: @image-url("./../images/data_types/purple_blocks_2.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "u16";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: u16. Size: 2 bytes. Also known as an unsigned short integer, unsigned short, or ushort.";
                    clicked => {
                    }
                }

                data-type-u16be := IconTextButton {
                    icon: @image-url("./../images/data_types/purple_blocks_2.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "u16 (BE)";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: u16 (Big Endian). Size: 2 bytes. Also known as an unsigned short integer, unsigned short, or ushort. Big Endian is generally only used in certain console emulators.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-u32 := IconTextButton {
                    icon: @image-url("./../images/data_types/purple_blocks_4.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "u32";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: u32. Size: 4 bytes. Also known as an unsigned integer, unsigned int, or uint.";
                    clicked => {
                    }
                }

                data-type-u32be := IconTextButton {
                    icon: @image-url("./../images/data_types/purple_blocks_4.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "u32 (BE)";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: u32 (Big Endian). Size: 4 bytes. Also known as an unsigned integer, unsigned int, or uint. Big Endian is generally only used in certain console emulators.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-u64 := IconTextButton {
                    icon: @image-url("./../images/data_types/purple_blocks_8.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "u64";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: u64. Size: 8 bytes. Also known as an unsigned long integer, unsigned long long, or ulong.";
                    clicked => {
                    }
                }

                data-type-u64be := IconTextButton {
                    icon: @image-url("./../images/data_types/purple_blocks_8.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "u64 (BE)";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: u64 (Big Endian). Size: 8 bytes. Also known as an unsigned long integer, unsigned long long, or ulong. Big Endian is generally only used in certain console emulators.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-f32 := IconTextButton {
                    icon: @image-url("./../images/data_types/orange_blocks_4.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "f32";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: f32. Size: 4 bytes. Also known as a Single-precision floating point.";
                    clicked => {
                    }
                }

                data-type-f32be := IconTextButton {
                    icon: @image-url("./../images/data_types/orange_blocks_4.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "f32 (BE)";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: f32 (Big Endian). Size: 4 bytes. Also known as a Single-precision floating point. Big Endian is generally only used in certain console emulators.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-f64 := IconTextButton {
                    icon: @image-url("./../images/data_types/orange_blocks_8.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "f64";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: f64. Size: 8 bytes. Also known as a Double-precision floating point.";
                    clicked => {
                    }
                }

                data-type-f64be := IconTextButton {
                    icon: @image-url("./../images/data_types/orange_blocks_8.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "f64 (BE)";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: f64 (Big Endian). Size: 8 bytes. Also known as a Double-precision floating point. Big Endian is generally only used in certain console emulators.";
                    clicked => {
                    }
                }
            }

            Row {
                data-type-bytes := IconTextButton {
                    // TODO: These should be purple
                    icon: @image-url("./../images/data_types/blue_blocks_array.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "u8 [ ]";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: u8[]. Size depends on the number of bytes provided. Also known as a byte[] or array of bytes. Represents a contiguous array of bytes.";
                    clicked => {
                    }
                }

                data-type-string := IconTextButton {
                    // TODO: Find your own damn icon
                    icon: @image-url("./../images/projects/static_type.png");
                    icon-width: 24px;
                    icon-height: 24px;
                    text: "string";
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    text-horizontal-alignment: left;
                    text-vertical-alignment: center;
                    tooltip-text: "Data Type: String. Size depends on the encoding and length of text. Represents any text.";
                    clicked => {
                    }
                }
            }
        }
    }
}
