import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "./../theme.slint";

import { ContextMenu } from "./../components/context_menu/context_menu.slint";
import { Button } from "./../components/buttons/button.slint";

export component ProcessQuickSelector inherits Rectangle {
    in property <string> selected-process-name;
    background: Theme.background-control;
    border-color: Theme.submenu-border;
    border-width: 1px;
    width: 192px;
    text-button := Button {
        width: 100%;
        height: 100%;
        clicked => {
            context-menu.show();
        }
        Text {
            horizontal-alignment: left;
            vertical-alignment: center;
            text: root.selected-process-name;
            color: Theme.foreground;
        }
    }

    context-menu := ContextMenu {
        x: text-button.x;
        y: text-button.y + text-button.height;
        width: 256px;
        content := VerticalBox {
            padding: 0px;
            spacing: 0px;
            detach-from-process := Button {
                height: 32px;
                clicked => {
                    context-menu.show();
                }
                Text {
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    text: @tr("== Detach from current process == ");
                    color: Theme.foreground;
                }
            }
        }
    }
}
