import { Theme } from "./../theme.slint";
import { HorizontalBox, VerticalBox, Palette, GridBox } from "std-widgets.slint";
import { ContextMenu } from "./../components/context_menu/context_menu.slint";
import { Button } from "../components/buttons/button.slint";

export component ScanConstraintButton inherits Button {
    in property <string> text;
    in property <image> icon;
    HorizontalLayout {
        HorizontalBox {
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: root.icon;
            }

            Text {
                color: Theme.foreground;
                horizontal-alignment: left;
                vertical-alignment: center;
                text: root.text;
            }
        }
    }
}
