import { Theme } from "../../theme.slint";
import { FocusTouchArea } from "../focus_touch_area.slint";
import { StateLayer } from "../state_layer.slint";
import { Tooltip } from "../tooltips/tooltip.slint";
import { Button } from "button.slint";

export component BevelButton {
    in property <bool> enabled: true;
    in property <length> border_radius: 4px;
    in property <length> border_bottom_left_radius: 0px;
    in property <length> border_bottom_right_radius: 0px;
    in property <length> border_top_left_radius: 0px;
    in property <length> border_top_right_radius: 0px;
    in property <length> border_width: 2px;
    in property <brush> background_color: Theme.background_control_primary;
    in property <brush> bevel_color: Theme.background_control_primary_dark;
    in property <brush> border_color: Theme.background_control_border;
    in property <string> tooltip_text;
    in property <length> bevel_height: 0px;
    in property <string> click_sound;
    in property <MouseCursor> mouse_cursor: pointer;
    callback clicked();
    callback moved();
    out property <bool> is_pressed: button.is_pressed;
    button_bottom := Rectangle {
        background <=> bevel_color;
        border_color <=> border_color;
        y: bevel_height;
        border_radius: root.border_radius;
        border_bottom_left_radius: root.border_radius + root.border_bottom_left_radius;
        border_bottom_right_radius: root.border_radius + root.border_bottom_right_radius;
        border_top_left_radius: root.border_radius + root.border_top_left_radius;
        border_top_right_radius: root.border_radius + root.border_top_right_radius;
    }

    button_top := Rectangle {
        background <=> root.background_color;
        border_color <=> root.border_color;
        border_radius: root.border_radius;
        border_bottom_left_radius: root.border_radius + root.border_bottom_left_radius;
        border_bottom_right_radius: root.border_radius + root.border_bottom_right_radius;
        border_top_left_radius: root.border_radius + root.border_top_left_radius;
        border_top_right_radius: root.border_radius + root.border_top_right_radius;
        border_width <=> root.border_width;
        button := Button {
            enabled <=> root.enabled;
            border_radius <=> root.border_radius;
            border_width <=> root.border_width;
            border_bottom_left_radius <=> root.border_bottom_left_radius;
            border_bottom_right_radius <=> root.border_bottom_right_radius;
            border_top_left_radius <=> root.border_top_left_radius;
            border_top_right_radius <=> root.border_top_right_radius;
            border_color <=> root.bevel_color;
            border_color_focused <=> root.bevel_color;
            tooltip_text <=> root.tooltip_text;
            click_sound <=> root.click_sound;
            mouse_cursor <=> root.mouse_cursor;
            width: 100%;
            height: 100%;
            clicked => {
                root.clicked();
            }
            moved => {
                root.moved();
            }
            @children
        }
    }
}
