import { Theme } from "../../theme.slint";
import { FocusTouchArea } from "../focus_touch_area.slint";
import { StateLayer } from "../state_layer.slint";
import { Tooltip } from "../tooltips/tooltip.slint";
import { Button } from "./button.slint";

export component BevelButton {
    in property <bool> enabled: true;
    in property <length> border-radius: 4px;
    in property <length> border-bottom-left-radius: 0px;
    in property <length> border-bottom-right-radius: 0px;
    in property <length> border-top-left-radius: 0px;
    in property <length> border-top-right-radius: 0px;
    in property <length> border-width: 2px;
    in property <brush> background-color: Theme.background-control-primary;
    in property <brush> bevel-color: Theme.background-control-primary-dark;
    in property <brush> border-color: Theme.background-control-border;
    in property <string> tooltip-text;
    in property <length> bevel-height: 0px;
    in property <string> click-sound;
    in property <MouseCursor> mouse-cursor: pointer;
    callback clicked();
    callback moved();
    out property <bool> is-pressed: button.is-pressed;
    button-bottom := Rectangle {
        background <=> bevel-color;
        border-color <=> border-color;
        y: bevel-height;
        border-radius: root.border-radius;
        border-bottom-left-radius: root.border-radius + root.border-bottom-left-radius;
        border-bottom-right-radius: root.border-radius + root.border-bottom-right-radius;
        border-top-left-radius: root.border-radius + root.border-top-left-radius;
        border-top-right-radius: root.border-radius + root.border-top-right-radius;
    }

    button-top := Rectangle {
        background <=> root.background-color;
        border-color <=> root.border-color;
        border-radius: root.border-radius;
        border-bottom-left-radius: root.border-radius + root.border-bottom-left-radius;
        border-bottom-right-radius: root.border-radius + root.border-bottom-right-radius;
        border-top-left-radius: root.border-radius + root.border-top-left-radius;
        border-top-right-radius: root.border-radius + root.border-top-right-radius;
        border-width <=> root.border-width;
        button := Button {
            enabled <=> root.enabled;
            border-radius <=> root.border-radius;
            border-width <=> root.border-width;
            border-bottom-left-radius <=> root.border-bottom-left-radius;
            border-bottom-right-radius <=> root.border-bottom-right-radius;
            border-top-left-radius <=> root.border-top-left-radius;
            border-top-right-radius <=> root.border-top-right-radius;
            border-color <=> root.bevel-color;
            border-color-focused <=> root.bevel-color;
            tooltip-text <=> root.tooltip-text;
            click-sound <=> root.click-sound;
            mouse-cursor <=> root.mouse-cursor;
            width: 100%;
            height: 100%;
            clicked => {
                root.clicked();
            }
            moved => {
                root.moved();
            }
            @children
        }
    }
}
