import { VerticalBox, HorizontalBox } from "std-widgets.slint";

import { Theme } from "../theme.slint";

export component GroupBox {
    in property <string> header_text: "Groupbox";
    in property <color> background: Theme.background_panel;
    in property <length> top_extra_padding: 4px;
    in property <length> inner_padding: 12px;
    Rectangle {
        border_color: Theme.submenu_border;
        background: root.background;
        border_radius: 4px;
        border_width: 1px;
        // This is how we get the border to "cull" __ we just paint a 1px rectangle over the groupbox border that matches the background color.
        HorizontalLayout {
            alignment: start;
            padding_left: 6px;
            header_fill := Rectangle {
                background: root.background;
                width: header.width + 12px;
                height: 1px;
                header := Text {
                    padding_top: 0px;
                    padding_bottom: 0px;
                    horizontal_alignment: left;
                    vertical_alignment: top;
                    text: root.header_text;
                    color: Theme.foreground;
                }
            }
        }

        grouping := Rectangle {
            VerticalLayout {
                padding_left: root.inner_padding;
                padding_right: root.inner_padding;
                padding_bottom: root.inner_padding;
                padding_top: root.top_extra_padding + root.inner_padding;
                spacing: 0px;
                @children
            }
        }
    }
}
