import { Theme } from "./../../theme.slint";
import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";
import { ContextMenu } from "./../context_menu/context_menu.slint";
import { TextButton } from "../../widgets/buttons/text_button.slint";

export component ToolbarMenuItem inherits HorizontalLayout {
    in property <string> text;
    in property <int> parent-toolbar-size;
    in-out property <[{text:string}]> items;
    text-button := TextButton {
        text: root.text;
        clicked => {
            context-menu.show();
        }
    }

    context-menu := ContextMenu {
        x: text-button.x;
        y: text-button.y + text-button.height;
        content := VerticalBox {
            padding: 0px;
            spacing: 0px;
            for item in items: TextButton {
                text: item.text;
            }
        }
    }
}
