import { Theme } from "./../../theme.slint";
import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

export component ToolbarMenu inherits Rectangle {
    height: 28px;
    background: Theme.background-primary;
    HorizontalLayout {
        spacing: 0px;
        alignment: start;
        content := HorizontalBox {
            padding: 0px;
            spacing: 0px;
            @children
        }
    }
}
