import { Theme } from "./../../theme.slint";
import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

export component ToolbarMenu inherits Rectangle {
    height: 24px;
    background: Theme.background-primary;
    HorizontalLayout {
        alignment: start;
        content := HorizontalBox {
            padding-left: 8px;
            padding-right: 8px;
            padding-top: 4px;
            padding-bottom: 4px;
            spacing: 20px;
            @children
        }
    }
}
