import { HorizontalBox, VerticalBox, Palette, ScrollView } from "std-widgets.slint";

import { Theme } from "../../theme.slint";
import { ProcessSelectorViewModelBindings, ProcessViewData } from "../../view_model_bindings.slint";

import { ProcessEntry } from "process_entry.slint";
import { ContextMenu } from "../../components/context_menu/context_menu.slint";
import { Button } from "../../components/buttons/button.slint";

export component ProcessQuickSelector inherits Rectangle {
    in property <string> selected-process-name;
    background: Theme.background-control;
    border-color: Theme.submenu-border;
    border-width: 1px;
    width: 192px;
    text-button := Button {
        width: 100%;
        height: 100%;
        clicked => {
            ProcessSelectorViewModelBindings.refresh-windowed-process-list();
            context-menu.show();
        }
        Text {
            horizontal-alignment: left;
            vertical-alignment: center;
            text: root.selected-process-name;
            color: Theme.foreground;
        }
    }

    context-menu := ContextMenu {
        x: text-button.x;
        y: text-button.y + text-button.height;
        Rectangle {
            background: Theme.background-control;
            border-color: Theme.submenu-border;
            border-width: 1px;
            width: 256px;
            min-height: 512px;
            ScrollView {
                padding: 0px;
                VerticalBox {
                    padding: 0px;
                    spacing: 0px;
                    for process-entry in ProcessSelectorViewModelBindings.windowed-processes: ProcessEntry {
                        process_view_data: process-entry;
                    }
                }
            }
        }
    }
}
