import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";
import { ProcessSelectorViewModelBindings, ProcessViewData } from "../../view_model_bindings.slint";

import { ProcessEntry } from "process_entry.slint";

export component ProcessSelectorView inherits Rectangle {
    content := VerticalBox {
        padding: 0px;
        spacing: 0px;
        for process-entry in ProcessSelectorViewModelBindings.processes: ProcessEntry {
            process_view_data: process-entry;
        }
    }
}
