import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";
import { WindowViewModelBindings } from "../../view_model_bindings.slint";

import { Button } from "../../components/buttons/button.slint";
import { TextField } from "../../components/input/text_field.slint";
import { ProcessQuickSelector } from "../process_selector/process_quick_selector.slint";
import { DataTypeSelector } from "../../controls/data_type_selector.slint";
import { ScanConstraintTypeSelector } from "../../controls/scan_constraint_selector.slint";
import { DockFocusCatcher } from "../docking/drag_and_drop/dock_focus_catcher.slint";

export component ShortcutBarView inherits Rectangle {
    in property <length> bottom-padding: 4px;
    height: 24px + root.bottom-padding;
    Rectangle {
        background: Theme.background-primary;
        HorizontalLayout {
            // Shortcut
            HorizontalBox {
                alignment: start;
                padding-left: 4px;
                padding-right: 0px;
                padding-top: 0px;
                padding-bottom: root.bottom-padding;
                spacing: 4px;
                select-process-button := Button {
                    width: 36px;
                    tooltip-text: @tr("Select Process");
                    click-sound: "";
                    clicked => {
                        WindowViewModelBindings.minimize();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        source: @image-url("../../images/select_process.png");
                    }
                }

                open-project-button := Button {
                    width: 36px;
                    tooltip-text: @tr("Open Project");
                    click-sound: "";
                    clicked => {
                        WindowViewModelBindings.minimize();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        source: @image-url("../../images/file_system/open_folder.png");
                    }
                }

                process-quick-selector := ProcessQuickSelector { }

                data-type-selector := DataTypeSelector { }

                new-scan-button := Button {
                    width: 36px;
                    tooltip-text: @tr("New Scan");
                    click-sound: "";
                    clicked => {
                        WindowViewModelBindings.minimize();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        source: @image-url("../../images/scans/scan_new.png");
                    }
                }

                collect-values-button := Button {
                    width: 36px;
                    tooltip-text: @tr("Collect Values");
                    click-sound: "";
                    clicked => {
                        WindowViewModelBindings.minimize();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        source: @image-url("../../images/scans/scan_collect_values.png");
                    }
                }

                scan-constraint-selector := ScanConstraintTypeSelector { }

                scan-value := TextField {
                    text-padding-top: 0px;
                    text-padding-bottom: 0px;
                    width: 192px;
                    preview-text: "Enter a scan value...";
                }

                start-scan-button := Button {
                    width: 36px;
                    tooltip-text: @tr("Start Scan");
                    click-sound: "";
                    clicked => {
                        WindowViewModelBindings.minimize();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        source: @image-url("../../images/navigation/right_arrow.png");
                    }
                }
            }
        }
    }

    DockFocusCatcher { }
}
