mod data_type_instruction_arm;
mod data_type_instruction_arm64;
mod data_type_instruction_thumb;

pub use data_type_instruction_arm::DataTypeInstructionArm;
pub use data_type_instruction_arm64::DataTypeInstructionArm64;
pub use data_type_instruction_thumb::DataTypeInstructionThumb;
