import { Theme } from "../../theme.slint";

import { StructViewerViewModelBindings } from "../../view_model_bindings.slint";
import { StructEntryView } from "struct_entry_view.slint";

export component StructViewerView inherits Rectangle {
    property <length> resizer_size: 4px;
    property <length> divider_size: 2px;
    pure function get_splitter_location() -> length {
        root.width * 0.5
    }
    content := VerticalLayout {
        padding: 0px;
        spacing: 0px;
        for next_struct in StructViewerViewModelBindings.structs_under_view: Rectangle {
            for next_field in next_struct.fields: StructEntryView {
                struct_entry: next_field;
                splitter_location: root.get_splitter_location();
            }
        }
    }

    Rectangle {
        x: root.get_splitter_location();
        y: 0;
        width: root.resizer_size;
        background: Theme.background_control;
        TouchArea {
            mouse_cursor: ew_resize;
            moved => {
                if (self.pressed && self.enabled) {
                }
            }
        }
    }
}
