import { Theme } from "../../../theme.slint";

import { DockRootViewModelBindings } from "../../../view_model_bindings.slint";

export component DockFocusCatcher inherits Rectangle {
    // Use a non_transparent first color to debug the focus catcher.
    background: DockRootViewModelBindings.active_dragged_window_id != "" ? Theme.transparent : Theme.transparent;
    TouchArea {
        mouse_cursor: MouseCursor.grabbing;
        enabled: DockRootViewModelBindings.active_dragged_window_id != "";
        pointer_event(event) => {
            if (event.kind == PointerEventKind.up) {
                DockRootViewModelBindings.active_dragged_window_id = "";
                DockRootViewModelBindings.is_dragging_window = false;
            }
        }
    }
}
