import { Theme } from "../theme.slint";

export component HSeparator {
    in_out property <bool> is_collapsed;
    callback clicked;
    Rectangle {
        height: is_collapsed ? 0px : 1px;
        width: 100%;
        background: Theme.submenu_border;
    }
}

export component VSeparator {
    in_out property <bool> is_collapsed;
    callback clicked;
    Rectangle {
        height: 100%;
        width: is_collapsed ? 0px : 1px;
        background: Theme.submenu_border;
    }
}
