import { Theme } from "../../theme.slint";

import { Button } from "../../components/buttons/button.slint";
import { ContextMenu } from "../context_menu/context_menu.slint";
import { FocusTouchArea } from "../focus_touch_area.slint";
import { StateLayer } from "../state_layer.slint";
import { FakeCheckbox } from "../checkboxes/fake_checkbox.slint";
import { DataTypeView, ConversionsViewModelBindings, ValidationViewModelBindings, ScannerViewModelBindings } from "../../view_model_bindings.slint";

export component DataValueBox {
    in_out property <DataTypeView> data_type;
    in_out property <bool> is_value_hex;
    in property <string> default_text;
    in property <string> preview_text;
    in property <length> text_padding_top: 4px;
    in property <length> text_padding_bottom: 4px;
    in property <length> text_padding_left: 8px;
    in property <length> text_padding_right: 8px;
    in property <TextHorizontalAlignment> text_horizontal_alignment: left;
    in property <TextVerticalAlignment> text_vertical_alignment: center;
    in property <color> background: Theme.background_primary;
    in property <color> foreground: Theme.foreground;
    in property <color> foreground_hex: Theme.hex_green;
    in property <color> foreground_preview: Theme.foreground_preview;
    in property <color> border_color: Theme.submenu_border;
    in property <color> invalid_color: Theme.error_red;
    public pure function get_value_text() -> string {
        return text_input.text;
    }
    public pure function is_value_valid(value: string) -> bool {
        // Empty string is OK, we dont want the cursor to go red for empty text.
        return value == "" || ValidationViewModelBindings.validate_data_value(root.data_type, value, ScannerViewModelBindings.is_value_hex);
    }
    forward_focus: touch_area;
    touch_area := FocusTouchArea {
        width: 100%;
        height: 100%;
        clicked => {
            text_input.focus();
        }
    }

    state_layer := StateLayer {
        width: 100%;
        height: 100%;
        pressed: touch_area.is_pressed || touch_area.enter_pressed;
        has_focus: touch_area.has_focus;
        has_hover: touch_area.has_hover;
    }

    input_border := Rectangle {
        background: root.background;
        border_color: root.border_color;
        border_radius: 2px;
        border_width: 1px;
        content_layer := HorizontalLayout {
            padding_top: root.text_padding_top;
            padding_bottom: root.text_padding_bottom;
            padding_left: root.text_padding_left;
            padding_right: root.text_padding_right;
            alignment: start;
            text_input := TextInput {
                text: root.default_text;
                horizontal_alignment: root.text_horizontal_alignment;
                vertical_alignment: root.text_vertical_alignment;
                color: root.is_value_valid(self.text) ? (root.is_value_hex ? root.foreground_hex : root.foreground) : root.invalid_color;
                single_line: true;
            }
        }

        HorizontalLayout {
            alignment: end;
            padding_right: 4px;
            VerticalLayout {
                alignment: center;
                base_systems_button := Button {
                    height: 24px;
                    width: 24px;
                    tooltip_text: @tr("Change base system...");
                    click_sound: "";
                    clicked => {
                        context_menu.show();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        source: @image_url("../../images/scans/convert_data_type.png");
                    }
                }
            }
        }
    }
            
    // Optional preview text to prompt the user with an input hint.
    preview_layer := HorizontalLayout {
        padding_top: root.text_padding_top;
        padding_bottom: root.text_padding_bottom;
        padding_left: root.text_padding_left;
        padding_right: root.text_padding_right;
        preview_text_display := Text {
            text: text_input.text == "" ? root.preview_text : "";
            horizontal_alignment: root.text_horizontal_alignment;
            vertical_alignment: root.text_vertical_alignment;
            color: root.foreground_preview;
        }
    }

    context_menu := ContextMenu {
        x: text_input.x;
        y: text_input.y + input_border.height;
        width: root.width;
        height: root.height;
        close_policy: PopupClosePolicy.close_on_click_outside;
        VerticalLayout {
            padding: 0px;
            spacing: 0px;
            Button {
                clicked => {
                    context_menu.close();
                    root.is_value_hex = false;
                }
                HorizontalLayout {
                    alignment: start;
                    padding: 8px;
                    spacing: 4px;
                    FakeCheckbox {
                        is_checked: !root.is_value_hex;
                    }

                    Text {
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        text: @tr("Dec");
                        color: Theme.foreground;
                    }
                }
            }

            Button {
                clicked => {
                    context_menu.close();
                    root.is_value_hex = true;
                }
                HorizontalLayout {
                    alignment: start;
                    padding: 8px;
                    spacing: 4px;
                    FakeCheckbox {
                        is_checked: root.is_value_hex;
                    }

                    Text {
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        text: @tr("Hex");
                        color: Theme.foreground;
                    }
                }
            }

            Button {
                HorizontalLayout {
                    alignment: start;
                    padding: 8px;
                    Text {
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        text: @tr("Convert to Dec");
                        color: Theme.foreground;
                    }
                }

                clicked => {
                    root.is_value_hex = false;
                    text_input.text = ConversionsViewModelBindings.convert_hex_to_dec(text_input.text);
                    context_menu.close();
                }
            }

            Button {
                HorizontalLayout {
                    alignment: start;
                    padding: 8px;
                    Text {
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        text: @tr("Convert to Hex");
                        color: Theme.foreground;
                    }
                }

                clicked => {
                    root.is_value_hex = true;
                    text_input.text = ConversionsViewModelBindings.convert_dec_to_hex(text_input.text);
                    context_menu.close();
                }
            }
        }
    }
}
