import { Theme } from "../../theme.slint";

import { DockedWindowView } from "../../views/docking/docked_window_view.slint";
import { OutputView } from "../../views/output/output_view.slint";
import { StructViewerView } from "../../views/struct_viewer/struct_viewer_view.slint";
import { ProcessSelectorView } from "../../views/process_selector/process_selector_view.slint";
import { ProjectExplorerView } from "../../views/project_explorer/project_explorer_view.slint";
import { ElementScannerView } from "../../views/element_scanner/element_scanner_view.slint";
import { PointerScannerView } from "../../views/pointer_scanner/pointer_scanner_view.slint";
import { SettingsView } from "../../views/settings/settings_view.slint";
import { DockRootViewModelBindings } from "../../view_model_bindings.slint";

export component DockRoot inherits Rectangle {
    changed width => {
        DockRootViewModelBindings.update_dock_root_width(root.width);
    }
    changed height => {
        DockRootViewModelBindings.update_dock_root_height(root.height);
    }
    background: Theme.background_primary;
    
    // 'Settings' window
    settings_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.settings_window;
        SettingsView { }
    }

    // 'ElementScanner' window
    element_scanner_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.element_scanner_window;
        ElementScannerView { }
    }

    // 'PointerScanner' window
    pointer_scanner_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.pointer_scanner_window;
        PointerScannerView { }
    }

    // 'Output' window
    output_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.output_window;
        OutputView { }
    }

    // 'ProcessSelector' window
    process_selector_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.process_selector_window;
        ProcessSelectorView { }
    }

    // 'StructViewer' window
    struct_viewer_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.struct_viewer_window;
        StructViewerView { }
    }

    // 'ProjectExplorer' window
    project_explorer_window := DockedWindowView {
        docked_window_data <=> DockRootViewModelBindings.project_explorer_window;
        ProjectExplorerView { }
    }
}
