import { Theme } from "../../theme.slint";
import { WindowViewModelBindings } from "../../view_model_bindings.slint";
import { Button } from "../../components/buttons/button.slint";

export component UndockedWindowTitleBarView inherits Rectangle {
    in property <string> title <=> title.text;
    height: 32px;
    Rectangle {
        border_top_left_radius: 8px;
        border_top_right_radius: 8px;
        background: Theme.background_primary;
        title_drag := TouchArea {
            double_clicked => {
                if (self.pressed && self.enabled) {
                    WindowViewModelBindings.double_clicked();
                }
            }
            moved => {
                if (self.pressed && self.enabled) {
                    WindowViewModelBindings.drag((title_drag.mouse_x - title_drag.pressed_x) / 1px, (title_drag.mouse_y - title_drag.pressed_y) / 1px);
                }
            }
        }

        HorizontalLayout {
            // Title
            HorizontalLayout {
                alignment: start;
                padding_left: 4px;
                spacing: 4px;
                title := Text {
                    vertical_alignment: center;
                    color: Theme.foreground;
                }
            }

            // Minimize/maximize/close
            HorizontalLayout {
                alignment: end;
                padding: 0px;
                spacing: 0px;
                minimize_button := Button {
                    width: 36px;
                    tooltip_text: @tr("Minimize");
                    click_sound: "";
                    clicked => {
                        WindowViewModelBindings.minimize();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        source: @image_url("../../images/window/minimize.png");
                    }
                }

                maximize_button := Button {
                    width: 36px;
                    tooltip_text: @tr("Maximize");
                    click_sound: "";
                    clicked => {
                        WindowViewModelBindings.minimize();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        source: @image_url("../../images/window/maximize.png");
                    }
                }

                close_button := Button {
                    width: 36px;
                    tooltip_text: @tr("Close");
                    click_sound: "";
                    clicked => {
                        WindowViewModelBindings.close();
                    }
                    Image {
                        width: 16px;
                        height: 16px;
                        horizontal_alignment: center;
                        vertical_alignment: center;
                        source: @image_url("../../images/window/close.png");
                    }
                }
            }
        }
    }
}
