import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { DockFocusCatcher } from "../docking/drag_and_drop/dock_focus_catcher.slint";

export component FooterView inherits Rectangle {
    height: 24px;
    Rectangle {
        border_bottom_left_radius: 8px;
        border_bottom_right_radius: 8px;
        background: Theme.border_blue;
    }

    DockFocusCatcher { }
}
