import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { DockFocusCatcher } from "../docking/drag_and_drop/dock_focus_catcher.slint";

export component FooterView inherits Rectangle {
    height: 24px;
    Rectangle {
        border-bottom-left-radius: 8px;
        border-bottom-right-radius: 8px;
        background: Theme.border-blue;
    }

    DockFocusCatcher { }
}
