import { HorizontalBox } from "std-widgets.slint";

import { Theme } from "../../theme.slint";
import { WindowViewModelBindings, DockRootViewModelBindings } from "../../view_model_bindings.slint";

import { FooterView } from "footer_view.slint";
import { TitleBarView } from "title_bar_view.slint";
import { ShortcutBarView } from "shortcut_bar_view.slint";

import { DockRoot } from "../docking/dock_root.slint";
import { HSeparator } from "../../components/separator.slint";
import { ToolbarMenu } from "../../components/toolbar_menu/toolbar_menu.slint";
import { ToolbarMenuCheckState } from "../../components/toolbar_menu/toolbar_menu_item.slint";

export component MainWindowView inherits Window {
    title: @tr("Squalr");
    default_font_family: Theme.default_font_family;
    default_font_size: Theme.font_size_p;
    default_font_weight: Theme.font_weight;
    preferred_width: 1280px;
    resize_border_width: 4px;
    preferred_height: 840px;
    background: transparent;
    no_frame: true;
    HorizontalLayout {
        VerticalLayout {
            title_bar := TitleBarView {
                title: @tr("Squalr");
            }

            toolbar_menu := ToolbarMenu {
                menus: [
                    {
                        header: "File",
                        items:[
                            { id: "select_project", text:"Select Project" },
                            { id: "export_project", text:"Export Project as Table..." },
                            { id: "exit", text: "Exit Squalr", has_separator: true }
                        ]
                    },
                    { header: "Layout", items:[{ id: "layout_reset", text:"Reset Layout" }] },
                    {
                        header: "Windows",
                        items:[
                            {
                                id: DockRootViewModelBindings.process_selector_window.identifier,
                                text:"Process Selector",
                                check_state: DockRootViewModelBindings.process_selector_window.is_visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.project_explorer_window.identifier,
                                text:"Project Explorer",
                                check_state: DockRootViewModelBindings.project_explorer_window.is_visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.property_viewer_window.identifier,
                                text:"Property Viewer",
                                check_state: DockRootViewModelBindings.property_viewer_window.is_visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.memory_viewer_window.identifier,
                                text:"Memory Viewer",
                                check_state: ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.output_window.identifier,
                                text:"Output",
                                check_state: DockRootViewModelBindings.output_window.is_visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.pointer_scan_results_window.identifier,
                                text:"Pointer Scan Results",
                                check_state: ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.scan_results_window.identifier,
                                text:"Scan Results",
                                check_state: DockRootViewModelBindings.scan_results_window.is_visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.settings_window.identifier,
                                text:"Settings",
                                check_state: DockRootViewModelBindings.settings_window.is_visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.snapshot_manager_window.identifier,
                                text:"Snapshot Manager",
                                check_state: ToolbarMenuCheckState.unchecked
                            },
                        ]
                    },
                    { header: "Scans", items:[{ id: "scans", text:"Pointer Scan" }] },
                    {
                        header: "Debugger",
                        items:[{ id: "disassembly", text:"Disassembly" }, { id: "code_tracer", text:"Code Tracer" }]
                    },
                ];
                onItemClicked(id) => {
                    if id == "exit" {
                        WindowViewModelBindings.close();
                    } else if id == "select_project" {
                    } else if id == "export_project" {
                    } else if id == "layout_reset" {
                        DockRootViewModelBindings.reset_layout();
                    } else if id == DockRootViewModelBindings.process_selector_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.process_selector_window.identifier);
                    } else if id == DockRootViewModelBindings.project_explorer_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.project_explorer_window.identifier);
                    } else if id == DockRootViewModelBindings.property_viewer_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.property_viewer_window.identifier);
                    } else if id == DockRootViewModelBindings.memory_viewer_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.memory_viewer_window.identifier);
                    } else if id == DockRootViewModelBindings.output_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.output_window.identifier);
                    } else if id == DockRootViewModelBindings.pointer_scan_results_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.pointer_scan_results_window.identifier);
                    } else if id == DockRootViewModelBindings.scan_results_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.scan_results_window.identifier);
                    } else if id == DockRootViewModelBindings.settings_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.settings_window.identifier);
                    } else if id == DockRootViewModelBindings.snapshot_manager_window.identifier {
                        DockRootViewModelBindings.toggle_visibility(DockRootViewModelBindings.snapshot_manager_window.identifier);
                    }
                }
            }

            shortcut_bar := ShortcutBarView { }

            dock_root := DockRoot { }

            footer := FooterView { }
        }
    }
}
