import { HorizontalBox } from "std-widgets.slint";

import { Theme } from "../../theme.slint";
import { WindowViewModelBindings, DockRootViewModelBindings } from "../../view_model_bindings.slint";

import { FooterView } from "./footer_view.slint";
import { TitleBarView } from "./title_bar_view.slint";
import { ShortcutBarView } from "./shortcut_bar_view.slint";

import { DockRoot } from "./../docking/dock_root.slint";
import { HSeparator } from "./../../components/separator.slint";
import { ToolbarMenu } from "./../../components/toolbar_menu/toolbar_menu.slint";
import { ToolbarMenuCheckState } from "./../../components/toolbar_menu/toolbar_menu_item.slint";

export component MainWindowView inherits Window {
    title: @tr("Squalr");
    default-font-family: "Segoe UI";
    default-font-size: Theme.font-size-p;
    default-font-weight: Theme.font-weight;
    preferred-width: 1280px;
    resize-border-width: 4px;
    preferred-height: 840px;
    background: transparent;
    no-frame: true;
    HorizontalLayout {
        VerticalLayout {
            title-bar := TitleBarView {
                title: @tr("Squalr");
            }

            toolbar-menu := ToolbarMenu {
                menus: [
                    {
                        header: "File",
                        items:[
                            { id: "select-project", text:"Select Project" },
                            { id: "export-project", text:"Export Project as Table..." },
                            { id: "exit", text: "Exit Squalr", has-separator: true }
                        ]
                    },
                    { header: "Layout", items:[{ id: "layout-reset", text:"Reset Layout" }] },
                    {
                        header: "Windows",
                        items:[
                            {
                                id: DockRootViewModelBindings.process-selector-window.identifier,
                                text:"Process Selector",
                                check-state: DockRootViewModelBindings.process-selector-window.is-visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.project-explorer-window.identifier,
                                text:"Project Explorer",
                                check-state: DockRootViewModelBindings.project-explorer-window.is-visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.property-viewer-window.identifier,
                                text:"Property Viewer",
                                check-state: DockRootViewModelBindings.property-viewer-window.is-visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.memory-viewer-window.identifier,
                                text:"Memory Viewer",
                                check-state: ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.output-window.identifier,
                                text:"Output",
                                check-state: DockRootViewModelBindings.output-window.is-visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.pointer-scan-results-window.identifier,
                                text:"Pointer Scan Results",
                                check-state: ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.scan-results-window.identifier,
                                text:"Scan Results",
                                check-state: DockRootViewModelBindings.scan-results-window.is-visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.settings-window.identifier,
                                text:"Settings",
                                check-state: DockRootViewModelBindings.settings-window.is-visible ? ToolbarMenuCheckState.checked : ToolbarMenuCheckState.unchecked
                            },
                            {
                                id: DockRootViewModelBindings.snapshot-manager-window.identifier,
                                text:"Snapshot Manager",
                                check-state: ToolbarMenuCheckState.unchecked
                            },
                        ]
                    },
                    { header: "Scans", items:[{ id: "scans", text:"Pointer Scan" }] },
                    {
                        header: "Debugger",
                        items:[{ id: "disassembly", text:"Disassembly" }, { id: "code-tracer", text:"Code Tracer" }]
                    },
                ];
                onItemClicked(id) => {
                    if id == "exit" {
                        WindowViewModelBindings.close();
                    } else if id == "select-project" {
                    } else if id == "export-project" {
                    } else if id == "layout-reset" {
                        DockRootViewModelBindings.reset-layout();
                    } else if id == DockRootViewModelBindings.process-selector-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.process-selector-window.identifier);
                    } else if id == DockRootViewModelBindings.project-explorer-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.project-explorer-window.identifier);
                    } else if id == DockRootViewModelBindings.property-viewer-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.property-viewer-window.identifier);
                    } else if id == DockRootViewModelBindings.memory-viewer-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.memory-viewer-window.identifier);
                    } else if id == DockRootViewModelBindings.output-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.output-window.identifier);
                    } else if id == DockRootViewModelBindings.pointer-scan-results-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.pointer-scan-results-window.identifier);
                    } else if id == DockRootViewModelBindings.scan-results-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.scan-results-window.identifier);
                    } else if id == DockRootViewModelBindings.settings-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.settings-window.identifier);
                    } else if id == DockRootViewModelBindings.snapshot-manager-window.identifier {
                        DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.snapshot-manager-window.identifier);
                    }
                }
            }

            shortcut-bar := ShortcutBarView { }

            dock-root := DockRoot { }

            footer := FooterView { }
        }
    }
}
