import { HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

import { Theme } from "../../theme.slint";

import { Button } from "../../components/buttons/button.slint";
import { TextField } from "../../components/input/text_field.slint";
import { ProcessQuickSelector } from "../process_selector/process_quick_selector.slint";
import { DataTypeSelector } from "../../controls/data_type_selector.slint";
import { ScanConstraintTypeSelector } from "../../controls/scan_constraint_selector.slint";
import { DockFocusCatcher } from "../docking/drag_and_drop/dock_focus_catcher.slint";
import { HexDecBox } from "../../components/hex_dec_box.slint";
import { DockRootViewModelBindings, ValueCollectorViewModelBindings, ManualScanViewModelBindings } from "../../view_model_bindings.slint";

export component ShortcutBarView inherits Rectangle {
    property <length> bar-height: 28px;
    property <length> bar-spacing: 4px;
    property <length> bottom-padding: 4px;
    property <length> flow-break-point: 800px;
    height: (root.width < flow-break-point ? bar-height * 2 + bar-spacing : bar-height) + root.bottom-padding;
    background: Theme.background-primary;
    // Shortcut
    top-bar := HorizontalBox {
        x: 0px;
        y: 0px;
        alignment: start;
        height: bar-height;
        padding-left: 4px;
        padding-right: 0px;
        padding-top: 0px;
        spacing: 4px;
        select-process-button := Button {
            height: bar-height;
            width: 36px;
            tooltip-text: @tr("Select Process");
            click-sound: "";
            clicked => {
                DockRootViewModelBindings.toggle-visibility(DockRootViewModelBindings.process-selector-window.identifier);
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: @image-url("../../images/select_process.png");
            }
        }

        open-project-button := Button {
            height: bar-height;
            width: 36px;
            tooltip-text: @tr("Open Project");
            click-sound: "";
            clicked => {
                // WindowViewModelBindings.minimize();
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: @image-url("../../images/file_system/open_folder.png");
            }
        }

        process-quick-selector := ProcessQuickSelector {
            height: bar-height;
        }

        new-scan-button := Button {
            height: bar-height;
            width: 36px;
            tooltip-text: @tr("New Scan");
            click-sound: "";
            clicked => {
                ManualScanViewModelBindings.new_scan(ManualScanViewModelBindings.active_data_type);
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: @image-url("../../images/scans/scan_new.png");
            }
        }

        collect-values-button := Button {
            height: bar-height;
            width: 36px;
            tooltip-text: @tr("Collect Values");
            click-sound: "";
            clicked => {
                ValueCollectorViewModelBindings.collect_values();
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: @image-url("../../images/scans/scan_collect_values.png");
            }
        }

        end-marker := Rectangle { }
    }

    // Second bar (wrappable)
    bottom-bar := HorizontalBox {
        x: root.width < flow-break-point ? 0px : end-marker.x;
        y: root.width < flow-break-point ? bar-height + bar-spacing : 0px;
        alignment: start;
        height: bar-height;
        padding-left: 4px;
        padding-right: 0px;
        padding-top: 0px;
        spacing: 4px;
        scan-constraint-selector := ScanConstraintTypeSelector {
            height: bar-height;
        }

        scan-value := HexDecBox {
            height: bar-height;
            text-padding-top: 0px;
            text-padding-bottom: 0px;
            width: 192px;
            preview-text: @tr("Enter a scan value...");
        }

        data-type-selector := DataTypeSelector {
            height: bar-height;
        }

        start-scan-button := Button {
            height: bar-height;
            width: 36px;
            tooltip-text: @tr("Start Scan");
            click-sound: "";
            clicked => {
                ManualScanViewModelBindings.start_scan(ManualScanViewModelBindings.active_scan_type, scan-value.get_value_text());
            }
            Image {
                width: 16px;
                height: 16px;
                horizontal-alignment: center;
                vertical-alignment: center;
                source: @image-url("../../images/navigation/right_arrow.png");
            }
        }
    }

    DockFocusCatcher { }
}
