import { Theme } from "../../../../theme.slint";

import { ConversionsViewModelBindings, ScanSettingsViewModelBindings, StringEncodingView } from "../../../../view_model_bindings.slint";
import { IconConverter } from "../../../../converters/icon_converter.slint";
import { Button } from "../../../../components/buttons/button.slint";
import { ContextMenu } from "../../../../components/context_menu/context_menu.slint";

export component SettingChooserStringEncodingEntry inherits Button {
    in property <StringEncodingView> string_encoding;
    callback onClicked;
    height: 24px;
    clicked => {
        ScanSettingsViewModelBindings.string_encoding = root.string_encoding;
        ScanSettingsViewModelBindings.string_encoding_changed(root.string_encoding);
        root.onClicked();
    }
    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            padding_left: 4px;
            padding_right: 8px;
            spacing: 8px;
            alignment: start;
            Text {
                color: Theme.foreground;
                horizontal_alignment: left;
                vertical_alignment: center;
                text: ConversionsViewModelBindings.get_string_encoding_string(root.string_encoding);
            }
        }
    }
}
